load("//tools/base/bazel:maven.bzl", "maven_repository")

maven_repository(
    name = "maven_repo",
    artifacts = [
        "//tools/base/backup-test/android-backup-runner",
        "//tools/base/backup-test/backup-test-api",
        "//tools/base/backup-test/backup-junit-engine",
    ],
)
