"""
Maven artifacts for compiling java and kotlin sources against in bazel

These are all resolved together to give a single, consistent compile and runtime classpath
for those bazel build and test steps. Artifacts added here behave as if they had also been
added to DATA in data.bzl also.

Only add things here if you need to use the artifact directly in the `deps` or `runtime_deps`
of a `(maven|kotlin|java)_library` rule, otherwise use DATA.
"""

# keep sorted
ARTIFACTS = [
    "androidx.annotation:annotation:1.1.0",
    "androidx.annotation:annotation-jvm:1.7.1",
    "androidx.compose.animation:animation-core-lint:1.8.0-alpha06",  # Compose Desktop Lint checks
    "androidx.compose.animation:animation-lint:1.8.0-alpha06",  # Compose Desktop Lint checks
    "androidx.compose.foundation:foundation-lint:1.8.0-alpha06",  # Compose Desktop Lint checks
    "androidx.compose.material:material-lint:1.8.0-alpha06",  # Compose Desktop Lint checks
    "androidx.compose.material3:material3-lint:1.4.0-alpha04",  # Compose Desktop Lint checks
    "androidx.compose.runtime:runtime-lint:1.8.0-alpha06",  # Compose Desktop Lint checks
    "androidx.compose.runtime:runtime-saveable-lint:1.8.0-alpha06",  # Compose Desktop Lint checks
    "androidx.compose.ui:ui-graphics-lint:1.8.0-alpha06",  # Compose Desktop Lint checks
    "androidx.compose.ui:ui-lint:1.8.0-alpha06",  # Compose Desktop Lint checks
    "androidx.compose.ui:ui-test-manifest-lint:1.8.0-alpha06",  # Compose Desktop Lint checks
    "androidx.compose.ui:ui-text-lint:1.8.0-alpha06",  # Compose Desktop Lint checks
    "androidx.core:core:1.1.0",
    "androidx.lint:lint-gradle:1.0.0-alpha01",
    "androidx.multidex:multidex:2.0.1",
    "androidx.test:runner:1.4.0",
    "androidx.test.uiautomator:uiautomator:2.3.0",
    "com.android.tools.build:bundletool:1.18.3",
    "com.android.tools.build.jetifier:jetifier-core:1.0.0-beta10",
    "com.android.tools.build.jetifier:jetifier-processor:1.0.0-beta10",
    "com.android.tools.build:transform-api:2.0.0-deprecated-use-gradle-api",
    "com.android.tools:common:31.13.0",  # Sherlock dependency
    "com.android.tools:desugar_jdk_libs:1.1.5",
    "com.android.tools:desugar_jdk_libs_configuration:1.1.5",
    "com.android.tools:desugar_jdk_libs_configuration_nio:2.0.2",
    "com.android.tools:desugar_jdk_libs_nio:2.0.2",
    "com.android.tools.fakeadbserver:fakeadbserver:31.13.0",  # Sherlock dependency
    "com.android.tools:r8:8.2.47",
    "com.android.tools.smali:smali-baksmali:3.0.9",
    "com.android.tools.smali:smali-dexlib2:3.0.9",
    "com.fasterxml:aalto-xml:1.3.0",
    "com.fasterxml.jackson.core:jackson-annotations:2.11.1",
    "com.fasterxml.jackson.core:jackson-core:2.11.1",
    "com.fasterxml.jackson.core:jackson-databind:2.11.1",
    "com.github.javaparser:javaparser-core:3.23.0",
    "com.github.rholder:guava-retrying:2.0.0",
    "com.github.rising3:semver:0.3.1",
    "com.google.api-client:google-api-client:1.35.2",
    "com.google.apis:google-api-services-cloudbilling:v1-rev20240119-2.0.0",
    "com.google.apis:google-api-services-cloudresourcemanager:v3-rev20230416-2.0.0",
    "com.google.apis:google-api-services-monitoring:v3-rev20230806-2.0.0",
    "com.google.apis:google-api-services-oauth2:v2-rev20200213-2.0.0",
    "com.google.apis:google-api-services-serviceusage:v1-rev20240220-2.0.0",
    "com.google.apis:google-api-services-storage:v1-rev20230301-2.0.0",
    "com.google.apis:google-api-services-testing:v1-rev20250327-2.0.0",
    "com.google.apis:google-api-services-toolresults:v1beta3-rev20230410-2.0.0",
    "com.google.auto:auto-common:0.10",
    "com.google.auto.value:auto-value:1.10.1",
    "com.google.auto.value:auto-value-annotations:1.10.1",
    "com.google.code.findbugs:jsr305:3.0.2",
    "com.google.code.gson:gson:2.11.0",
    "com.google.crypto.tink:tink:1.7.0",
    "com.google.dagger:dagger-compiler:2.48",
    "com.google.devtools.ksp:symbol-processing-gradle-plugin:2.2.10-2.0.2",  # AGP dependencies
    "com.google.errorprone:error_prone_annotations:2.28.0",
    "com.google.flatbuffers:flatbuffers-java:1.12.0",
    "com.google.flogger:flogger:0.8",
    "com.google.flogger:flogger-system-backend:0.8",
    "com.google.guava:guava:33.3.1-jre",
    "com.google.guava:guava-testlib:33.3.1-jre",
    "com.google.http-client:google-http-client:1.43.3",
    "com.google.http-client:google-http-client-apache-v2:1.42.0",
    "com.google.http-client:google-http-client-gson:1.43.3",
    "com.google.http-client:google-http-client-jackson2:1.22.0",
    "com.google.jimfs:jimfs:1.1",
    "com.google.oauth-client:google-oauth-client:1.35.0",
    "com.google.oauth-client:google-oauth-client-java6:1.35.0",
    "com.google.protobuf:protobuf-bom:pom:3.25.5",
    "com.google.protobuf:protobuf-gradle-plugin:0.9.4",
    "com.google.protobuf:protobuf-java:3.25.5",
    "com.google.protobuf:protobuf-java-util:3.25.5",
    "com.google.protobuf:protobuf-parent:pom:3.25.5",
    "com.google.protobuf:protoc:exe:linux-x86_64:3.22.3",
    "com.google.protobuf:protoc:exe:osx-aarch_64:3.22.3",
    "com.google.protobuf:protoc:exe:osx-x86_64:3.22.3",
    "com.google.protobuf:protoc:exe:windows-x86_64:3.22.3",
    "com.google.re2j:re2j:1.7",
    "com.google.testing.compile:compile-testing:0.16",
    "com.google.testing.platform:android-device-provider-local:0.0.9-alpha03",
    "com.google.testing.platform:android-driver-instrumentation:0.0.9-alpha03",
    "com.google.testing.platform:android-test-plugin:0.0.9-alpha03",
    "com.google.testing.platform:core:0.0.9-alpha03",
    "com.google.testing.platform:core-proto:0.0.9-alpha03",
    "com.google.testing.platform:launcher:0.0.9-alpha03",
    "com.google.truth.extensions:truth-java8-extension:0.42",
    "com.google.truth.extensions:truth-proto-extension:0.42",  # Sherlock dependency
    "com.google.truth:truth:0.42",
    "com.googlecode.jarjar:jarjar:1.3",
    "com.googlecode.juniversalchardet:juniversalchardet:1.0.3",
    "com.nothome:javaxdelta:2.0.1",
    "com.squareup:javapoet:1.10.0",
    "com.squareup:javawriter:2.5.0",
    "com.squareup.okhttp:okhttp:2.5.0",
    "com.squareup.okhttp3:mockwebserver:4.12.0",
    "com.squareup.okhttp3:okhttp:4.12.0",
    "com.squareup.okio:okio:1.15.0",
    "com.squareup.okio:okio-jvm:3.0.0",
    "commons-cli:commons-cli:1.4",
    "commons-io:commons-io:2.16.1",
    "commons-lang:commons-lang:2.6",
    "commons-logging:commons-logging:1.2",
    "gradle.plugin.org.jetbrains.gradle.plugin.idea-ext:gradle-idea-ext:0.8.1",
    "io.github.oshai:kotlin-logging-jvm:7.0.0",
    "io.grpc:grpc-all:1.69.1",
    "io.grpc:grpc-api:1.69.1",
    "io.grpc:grpc-auth:1.69.1",
    "io.grpc:grpc-context:1.69.1",
    "io.grpc:grpc-core:1.69.1",
    "io.grpc:grpc-inprocess:1.69.1",
    "io.grpc:grpc-netty:1.69.1",
    "io.grpc:grpc-netty-shaded:1.69.1",
    "io.grpc:grpc-okhttp:1.69.1",
    "io.grpc:grpc-protobuf:1.69.1",
    "io.grpc:grpc-protobuf-lite:1.69.1",
    "io.grpc:grpc-stub:1.69.1",
    "io.grpc:protoc-gen-grpc-java:exe:linux-x86_64:1.57.0",
    "io.grpc:protoc-gen-grpc-java:exe:osx-aarch_64:1.57.0",
    "io.grpc:protoc-gen-grpc-java:exe:osx-x86_64:1.57.0",
    "io.grpc:protoc-gen-grpc-java:exe:windows-x86_64:1.57.0",
    "io.modelcontextprotocol:kotlin-sdk:0.5.0",
    "io.netty:netty-all:4.1.115.Final",
    "io.netty:netty-buffer:4.1.115.Final",
    "io.netty:netty-codec:4.1.115.Final",
    "io.netty:netty-codec-http:4.1.115.Final",
    "io.netty:netty-codec-http2:4.1.115.Final",
    "io.netty:netty-codec-socks:4.1.115.Final",
    "io.netty:netty-common:4.1.115.Final",
    "io.netty:netty-handler:4.1.115.Final",
    "io.netty:netty-handler-proxy:4.1.115.Final",
    "io.netty:netty-resolver:4.1.115.Final",
    "io.netty:netty-transport:4.1.115.Final",
    "io.opencensus:opencensus-api:0.21.0",
    "io.opencensus:opencensus-contrib-grpc-metrics:0.21.0",
    "io.perfmark:perfmark-api:0.17.0",
    "it.unimi.dsi:fastutil:8.4.0",
    "jakarta.xml.bind:jakarta.xml.bind-api:2.3.2",
    "javax.annotation:javax.annotation-api:1.3.2",
    "javax.inject:javax.inject:1",
    "javax.servlet:javax.servlet-api:3.0.1",
    "javax.xml.bind:jaxb-api:2.3.1",
    "joda-time:joda-time:2.10.10",
    "junit:junit:4.13.2",
    "log4j:log4j:1.2.17",
    "net.java.dev.jna:jna:5.6.0",
    "net.java.dev.jna:jna-platform:5.6.0",
    "net.sf.jopt-simple:jopt-simple:4.9",
    "net.sf.kxml:kxml2:2.3.0",
    "net.sf.proguard:proguard-gradle:5.2.1",
    "nl.jqno.equalsverifier:equalsverifier:3.15.6",
    "org.apache.bcel:bcel:6.9.0",
    "org.apache.commons:commons-compress:1.27.1",
    "org.apache.httpcomponents:httpclient:4.5.6",
    "org.apache.httpcomponents:httpcore:4.4.10",
    "org.apache.httpcomponents:httpmime:4.5.6",
    "org.apache.maven:maven-aether-provider:3.3.9",
    "org.apache.maven:maven-model-builder:3.9.1",
    "org.bouncycastle:bcpkix-jdk18on:1.79",
    "org.bouncycastle:bcprov-jdk18on:1.79",
    "org.bytedeco:ffmpeg:7.1.1-1.5.12",
    "org.codehaus.groovy:groovy-all:pom:3.0.22",
    "org.commonmark:commonmark:0.24.0",
    "org.eclipse.aether:aether-connector-basic:1.0.2.v20150114",
    "org.eclipse.aether:aether-transport-file:1.0.2.v20150114",
    "org.eclipse.aether:aether-transport-http:1.0.2.v20150114",
    "org.eclipse.elk:org.eclipse.elk.alg.layered:0.3.0",
    "org.eclipse.elk:org.eclipse.elk.core:0.3.0",
    "org.eclipse.elk:org.eclipse.elk.graph:0.3.0",
    "org.eclipse.emf:org.eclipse.emf.common:2.12.0",
    "org.eclipse.emf:org.eclipse.emf.ecore:2.12.0",
    "org.glassfish.jaxb:jaxb-runtime:2.3.2",
    "org.glassfish.jaxb:jaxb-xjc:2.3.2",
    "org.gradle:gradle-tooling-api:9.2.1",
    "org.hamcrest:hamcrest:2.2",
    "org.hamcrest:hamcrest-core:1.3",
    "org.hamcrest:hamcrest-library:1.3",
    "org.hdrhistogram:HdrHistogram:2.1.12",
    "org.jacoco:org.jacoco.agent:0.8.13",
    "org.jacoco:org.jacoco.build:pom:0.8.13",
    "org.jacoco:org.jacoco.core:0.8.13",
    "org.jacoco:org.jacoco.report:0.8.13",
    "org.jetbrains.dokka:dokka-core:1.4.32",
    "org.jetbrains.intellij.deps:asm-all:8.0.1",
    "org.jetbrains.kotlin:compose-compiler-gradle-plugin:2.2.10",  # AGP dependencies
    "org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin:pom:2.2.10",  # AGP dependencies
    "org.jetbrains.kotlin:kotlin-build-tools-impl:2.2.10",  # AGP dependencies
    "org.jetbrains.kotlin:kotlin-compiler:2.2.10",  # AGP dependencies
    "org.jetbrains.kotlin:kotlin-gradle-plugin-api:2.2.10",  # AGP dependencies
    "org.jetbrains.kotlin:kotlin-reflect:2.2.10",  # AGP dependencies
    "org.jetbrains.kotlin:kotlin-stdlib:2.2.10",  # AGP dependencies
    "org.jetbrains.kotlin:kotlin-test:2.2.10",  # AGP dependencies
    "org.jetbrains.kotlin:kotlin-test-junit:2.2.10",  # AGP dependencies
    "org.jetbrains.kotlinx:kotlinx-cli-jvm:0.3.1",
    "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.7.1",
    "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4",
    "org.jetbrains.kotlinx:kotlinx-coroutines-guava:1.6.4",
    "org.jetbrains.kotlinx:kotlinx-coroutines-test-jvm:1.6.4",
    "org.jetbrains.kotlinx:kotlinx-io-bytestring-jvm:0.6.0",
    "org.jetbrains.kotlinx:kotlinx-io-core-jvm:0.6.0",
    "org.jetbrains:markdown:pom:0.2.1",
    "org.jspecify:jspecify:0.2.0",
    "org.junit.platform:junit-platform-engine:1.12.0",
    "org.junit.platform:junit-platform-launcher:1.12.0",
    "org.junit.platform:junit-platform-reporting:1.12.0",
    "org.mockito.kotlin:mockito-kotlin:5.4.0",
    "org.mockito:mockito-core:5.12.0",
    "org.mortbay.jetty:jetty:6.1.26",
    "org.ow2.asm:asm:9.8",
    "org.ow2.asm:asm-analysis:9.8",
    "org.ow2.asm:asm-bom:pom:9.8",
    "org.ow2.asm:asm-commons:9.8",
    "org.ow2.asm:asm-tree:9.8",
    "org.ow2.asm:asm-util:9.8",
    "org.robolectric:robolectric:4.14.1",
    "org.slf4j:slf4j-simple:1.7.2",
    "org.tensorflow:tensorflow-lite-metadata:0.2.0",
    "org.tomlj:tomlj:1.1.0",
    "org.xerial:sqlite-jdbc:3.43.0.0",
]
