apply plugin: 'com.android.application'

android {
    namespace = "com.android.prefabaartest"
    compileSdkVersion libs.versions.latestCompileSdk.get().toInteger()
    buildToolsVersion = libs.versions.buildToolsVersion.get()

    defaultConfig {
        minSdkVersion 21
        targetSdkVersion libs.versions.latestCompileSdk.get()

    }

    buildFeatures {
        prefab = true
    }
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib:${libs.versions.kotlinVersion.get()}"
    implementation project(':curl')
    implementation project(':jsoncpp')
    implementation project(':openssl')
}
