load("//tools/base/bazel:bazel.bzl", "iml_module")

# managed by go/iml_to_build
iml_module(
    name = "studio.android.sdktools.backup.bmgr.parser",
    srcs = ["src"],
    iml_files = ["android.sdktools.backup.bmgr.parser.iml"],
    visibility = ["//visibility:public"],
    # do not sort: must match IML order
    deps = ["@intellij//:intellij-sdk"],
)
