/*
 * Copyright (C) 2024 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.android.tools.render.discovery

import com.android.tools.render.StandaloneRenderModelModule
import com.android.tools.render.compose.ComposeScreenshot
import org.objectweb.asm.AnnotationVisitor
import org.objectweb.asm.ClassReader
import org.objectweb.asm.ClassVisitor
import org.objectweb.asm.MethodVisitor
import org.objectweb.asm.Opcodes
import org.objectweb.asm.Type

/** Discovers Compose preview annotation parameters for a method from compiled bytecode. */
class PreviewDiscoveryEngine(private val module: StandaloneRenderModelModule) {

  private val classLoader: ClassLoader
    get() = module.environment.moduleClassLoaderManager.getShared(this::class.java.classLoader).classLoader

  companion object {
    /** Maximum number of previews allowed to be discovered for a single method to prevent DAG exponential expansion. */
    private const val MAX_DISCOVERED_PREVIEWS = 100

    private const val PREVIEW_DESC = "Landroidx/compose/ui/tooling/preview/Preview;"

    /**
     * Synthetic container annotation descriptor generated by the Kotlin/Java compiler when multiple repeatable `@Preview` annotations are
     * declared on the same method (e.g. `@Preview @Preview`).
     */
    private const val PREVIEW_CONTAINER_DESC = "Landroidx/compose/ui/tooling/preview/Preview\$Container;"

    /** Descriptor for Jetpack Compose's `@PreviewParameter` annotation. */
    private const val PREVIEW_PARAMETER_DESC = "Landroidx/compose/ui/tooling/preview/PreviewParameter;"
  }

  /**
   * Discovers all `@Preview` annotations declared on [methodFQN] from bytecode, extracting their parameters into [ComposeScreenshot]s.
   * Supports single previews, repeatable multi-previews, custom MultiPreview class annotations, and method parameter annotations such as
   * `@PreviewParameter`.
   */
  fun discoverAllPreviews(methodFQN: String, previewId: String? = null): List<ComposeScreenshot> {
    val className = methodFQN.substringBeforeLast(".")
    val methodName = methodFQN.substringAfterLast(".")

    val classBytes = findClassBytes(className) ?: return emptyList()

    val discoveredPreviews = mutableListOf<ComposeScreenshot>()
    val resolvedPreviewId = previewId ?: methodName

    val classReader = ClassReader(classBytes)
    classReader.accept(
      object : ClassVisitor(Opcodes.ASM9) {
        override fun visitMethod(
          access: Int,
          name: String,
          descriptor: String,
          signature: String?,
          exceptions: Array<out String>?,
        ): MethodVisitor? {
          if (name != methodName) return null
          if ((access and Opcodes.ACC_SYNTHETIC) != 0) return null

          val previewParamsList = mutableListOf<Map<String, String>>()
          val previewParameterAttributes = mutableMapOf<String, String>()
          val traversalPath = mutableSetOf<String>()

          return object : MethodVisitor(Opcodes.ASM9) {
            override fun visitAnnotation(desc: String, visible: Boolean): AnnotationVisitor? {
              return handleAnnotation(desc, traversalPath, previewParamsList)
            }

            override fun visitParameterAnnotation(parameter: Int, desc: String, visible: Boolean): AnnotationVisitor? {
              if (desc == PREVIEW_PARAMETER_DESC) {
                return createPreviewParameterVisitor(previewParameterAttributes)
              }
              return null
            }

            override fun visitEnd() {
              val methodParams = if (previewParameterAttributes.isNotEmpty()) listOf(previewParameterAttributes) else emptyList()
              for (previewParams in previewParamsList) {
                discoveredPreviews.add(
                  ComposeScreenshot(
                    methodFQN = methodFQN,
                    methodParams = methodParams,
                    previewParams = previewParams,
                    previewId = resolvedPreviewId,
                  )
                )
              }
            }
          }
        }
      },
      ClassReader.SKIP_CODE or ClassReader.SKIP_DEBUG or ClassReader.SKIP_FRAMES,
    )

    return discoveredPreviews
  }

  /**
   * Routes an annotation [desc] encountered during traversal:
   * - Direct `@Preview`: Extracts its preview parameters.
   * - Repeatable `@Preview$Container`: Traverses the container array of `@Preview` annotations.
   * - Custom MultiPreview: Recursively inspects the annotation class bytecode if [isPotentialMultiPreview] matches.
   */
  private fun handleAnnotation(
    desc: String,
    traversalPath: MutableSet<String>,
    discoveredList: MutableList<Map<String, String>>,
  ): AnnotationVisitor? {
    if (discoveredList.size >= MAX_DISCOVERED_PREVIEWS) {
      return null
    }

    when (desc) {
      PREVIEW_DESC -> {
        val previewParams = mutableMapOf<String, String>()
        discoveredList.add(previewParams)
        return createPreviewAnnotationVisitor(previewParams)
      }
      PREVIEW_CONTAINER_DESC -> {
        return createPreviewContainerVisitor(discoveredList)
      }
      else -> {
        if (isPotentialMultiPreview(desc)) {
          val annotationClassName = Type.getType(desc).className
          discoverFromAnnotationClass(annotationClassName, traversalPath, discoveredList)
        }
        return null
      }
    }
  }

  /**
   * Loads bytecode for [annotationClassName] and traverses its class-level annotations to discover nested `@Preview` or MultiPreview
   * definitions. Tracks [traversalPath] on the active recursion call stack to safely prevent infinite recursion on circular references.
   */
  private fun discoverFromAnnotationClass(
    annotationClassName: String,
    traversalPath: MutableSet<String>,
    discoveredList: MutableList<Map<String, String>>,
  ) {
    if (discoveredList.size >= MAX_DISCOVERED_PREVIEWS) {
      return
    }

    if (traversalPath.contains(annotationClassName)) {
      // Circular dependency detected on the active call stack (e.g. A -> B -> A)
      return
    }

    val classBytes = findClassBytes(annotationClassName) ?: return

    try {
      traversalPath.add(annotationClassName)
      val classReader = ClassReader(classBytes)
      classReader.accept(
        object : ClassVisitor(Opcodes.ASM9) {
          override fun visitAnnotation(desc: String, visible: Boolean): AnnotationVisitor? {
            return handleAnnotation(desc, traversalPath, discoveredList)
          }
        },
        ClassReader.SKIP_CODE or ClassReader.SKIP_DEBUG or ClassReader.SKIP_FRAMES,
      )
    } finally {
      traversalPath.remove(annotationClassName)
    }
  }

  /**
   * Creates an [AnnotationVisitor] to traverse the `value` array of a synthetic `@Preview$Container` annotation and extract all nested
   * `@Preview` annotations into [discoveredList].
   */
  private fun createPreviewContainerVisitor(discoveredList: MutableList<Map<String, String>>): AnnotationVisitor {
    return object : AnnotationVisitor(Opcodes.ASM9) {
      override fun visitArray(name: String?): AnnotationVisitor {
        return object : AnnotationVisitor(Opcodes.ASM9) {
          override fun visitAnnotation(name: String?, descriptor: String?): AnnotationVisitor? {
            if (discoveredList.size >= MAX_DISCOVERED_PREVIEWS) {
              return null
            }
            if (descriptor == PREVIEW_DESC) {
              val previewParams = mutableMapOf<String, String>()
              discoveredList.add(previewParams)
              return createPreviewAnnotationVisitor(previewParams)
            }
            return null
          }
        }
      }
    }
  }

  /**
   * Optimization to avoid loading and parsing bytecode for standard runtime, compiler, and framework annotations (e.g. `java.*`,
   * `kotlin.*`, `androidx.compose.runtime.*`) that can never lead to a MultiPreview definition.
   *
   * Matches the MultiPreview traversal filtering used in Android Studio (`couldBeMultiPreviewAnnotation`).
   */
  private fun isPotentialMultiPreview(desc: String): Boolean {
    return desc.startsWith("L") &&
      !desc.startsWith("Ljava/") &&
      !desc.startsWith("Ljavax/") &&
      !desc.startsWith("Lkotlin/") &&
      !desc.startsWith("Lkotlinx/") &&
      !desc.startsWith("Landroidx/compose/runtime/") &&
      !desc.startsWith("Landroidx/annotation/") &&
      !desc.startsWith("Lorg/intellij/") &&
      !desc.startsWith("Lorg/jetbrains/")
  }

  /**
   * Creates an [AnnotationVisitor] that extracts parameter key-value pairs from a `@Preview` annotation into the provided [previewParams]
   * map.
   */
  private fun createPreviewAnnotationVisitor(previewParams: MutableMap<String, String>): AnnotationVisitor {
    return object : AnnotationVisitor(Opcodes.ASM9) {
      override fun visit(name: String?, value: Any?) {
        if (name != null && value != null) {
          previewParams[name] =
            when (value) {
              is Type -> value.className
              else -> value.toString()
            }
        }
      }

      override fun visitEnum(name: String?, descriptor: String?, value: String?) {
        if (name != null && value != null) {
          previewParams[name] = value
        }
      }
    }
  }

  /** Creates an [AnnotationVisitor] that extracts attributes from a `@PreviewParameter` annotation. */
  private fun createPreviewParameterVisitor(paramMap: MutableMap<String, String>): AnnotationVisitor {
    return object : AnnotationVisitor(Opcodes.ASM9) {
      override fun visit(name: String?, value: Any?) {
        if (name == null || value == null) return
        paramMap[name] =
          when (value) {
            is Type -> value.className
            else -> value.toString()
          }
      }
    }
  }

  /**
   * Retrieves raw .class bytes from the [classLoader] for [className].
   *
   * Tries direct package path first (e.g. `com/example/MyClass.class`), then falls back to replacing dots with `$` from right to left to
   * support nested and companion classes (e.g. `MyClass$Companion.class`).
   */
  private fun findClassBytes(className: String): ByteArray? {
    // 1. First attempt: standard package path where all dots are package separators (com/example/MyClass.class)
    val directResource = "${className.replace('.', '/')}.class"
    classLoader.getResourceAsStream(directResource)?.use {
      return it.readBytes()
    }

    // 2. Fallback: handle inner/nested classes and companion objects by replacing dots with '$' from right to left
    // (e.g. "com.example.MyClass.Inner" -> "com/example/MyClass$Inner.class")
    var candidate = className
    while (candidate.contains('.')) {
      val idx = candidate.lastIndexOf('.')
      candidate = candidate.substring(0, idx) + "$" + candidate.substring(idx + 1)
      val resource = "${candidate.replace('.', '/')}.class"
      classLoader.getResourceAsStream(resource)?.use {
        return it.readBytes()
      }
    }
    return null
  }
}
