apply plugin: 'com.android.library'

android {
    namespace = "com.example.mylibrary"
    compileSdkVersion libs.versions.latestCompileSdk.get().toInteger()
    buildToolsVersion = libs.versions.buildToolsVersion.get()

    defaultConfig {
        minSdkVersion 15
        //noinspection ExpiringTargetSdkVersion,ExpiredTargetSdkVersion
        targetSdkVersion 21
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
}

androidComponents {
    onVariants(selector().all()) { variant ->
        def placeholders = ["localApplicationId" : "com.example.manifest_merger_example.flavor", "myPath": "/flavor"]
	if (variant.androidTest != null) {
            variant.androidTest.manifestPlaceholders.putAll(placeholders)
        }
    }
}

dependencies {
    testImplementation 'junit:junit:4.12'
    androidTestImplementation "androidx.test:runner:1.4.0-alpha06"
    androidTestImplementation "androidx.test:rules:1.4.0-alpha06"
}

