/*
 * Copyright (C) 2021 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

syntax = "proto3";

package com.android.tools.utp.plugins.result.listener.gradle.proto;

import "google/protobuf/any.proto";

option java_package = 'com.android.tools.utp.plugins.result.listener.gradle.proto';
option java_outer_classname = 'GradleAndroidTestResultListenerConfigProto';

// A configuration of GradleAndroidTestResultListener plugin.
message GradleAndroidTestResultListenerConfig {
    // A device ID to listen to for test results.
    string deviceId = 5;

    // A device name, used in the XML test report.
    string deviceName = 6;

    // A unique name for this test shard, used as the test suite name in the XML report.
    string deviceShardName = 7;

    // A project path, used in the XML test report.
    string gradleProjectPath = 8;

    // A variant name, used in the XML test report.
    string variantName = 9;

    // When enabled, it prints out base64 encoded test events to standard output.
    bool enableUtpTestReportingForAndroidStudio = 10;

    // A directory where XML test reports should be generated.
    string xmlTestReportOutputDirectoryPath = 11;

    // An output file where the binary test-result.pb for this run should be written.
    string utpResultProtoOutputFilePath = 12;

    // Obsolete fields.
    reserved 1, 2, 3, 4;
}
