def artifactType = Attribute.of("artifactType", String.class)

allprojects {
    afterEvaluate { p ->
        p.plugins.withId("com.android.application") {
            p.androidComponents {
                onVariants(selector().all(), { v ->
                    p.tasks.register("${v.name}ExtractClasspath") {
                        def runtimeClasses = v.runtimeConfiguration.incoming.artifactView { av ->
                            av.attributes {
                                attribute(artifactType, "android-classes-jar")
                            }
                        }.files

                        it.inputs.files(runtimeClasses)

                        doFirst {
                            try (def deps = new FileOutputStream(new File("deps.txt"))) {
                                def capName = v.name.capitalize()
                                deps.write("${buildDir}/intermediates/compile_app_classes_jar/${v.name}/bundle${capName}ClassesToCompileJar/classes.jar\n".getBytes())
                                deps.write("${buildDir}/intermediates/compile_and_runtime_r_class_jar/${v.name}/process${capName}Resources/R.jar\n".getBytes())
                                def fileNames = runtimeClasses.files.collect { "${it}".toString() }
                                fileNames.forEach {
                                    deps.write("${it}\n".getBytes())
                                }
                            }
                        }
                    }
                })
            }
        }
    }
}
