module(
    name = "android_studio",
)

bazel_dep(name = "platforms", version = "0.0.10")
bazel_dep(name = "rules_cc", version = "0.0.15")
bazel_dep(name = "rules_python", version = "1.1.0")
bazel_dep(name = "rules_license", version = "1.0.0")
bazel_dep(name = "rules_java", version = "8.6.3")
bazel_dep(name = "rules_robolectric", version = "4.14.1.2")

include("//tools/base/bazel/bzlmod:external.MODULE.bazel")

include("//tools/base/bazel/bzlmod:toolchains.MODULE.bazel")

include("//tools/base/bazel/bzlmod:prebuilts.MODULE.bazel")

include("//tools/base/bazel/bzlmod:coverage.MODULE.bazel")

include("//tools/base/bazel/bzlmod:sdk.MODULE.bazel")

include("//tools:vendor.MODULE.bazel")
