// ATTENTION -- hash value of this file is checked in the corresponding
// integration test. Please make sure any changes you make here are
// backwards compatible.

apply from: "../commonHeader.gradle"
buildscript { apply from: "../commonBuildScript.gradle" }

apply plugin: 'com.android.application'

android {
    namespace = "com.android.tests.basic"
    compileSdkVersion libs.versions.latestCompileSdk.get().toInteger()
    buildToolsVersion = libs.versions.buildToolsVersion.get()
}

abstract class SingleOutputTask extends DefaultTask {
    @OutputDirectory
    abstract DirectoryProperty getOutputFolder()

    @TaskAction
    void taskAction() {
        // do nothing; task is only for setting the output folder
    }
}

androidComponents {
    onVariants(selector().all()) { variant ->
        def javaGenerationTask = tasks.register("generatedJavaFor${variant.name.capitalize()}", SingleOutputTask) {
            outputFolder.set(project.layout.buildDirectory.dir("customCode/${variant.name}"))
        }
        variant.sources.java.addGeneratedSourceDirectory(javaGenerationTask, { it.getOutputFolder() })

        if (variant.unitTest != null) {
            def unitTestTask1 = tasks.register("generatedJavaFor${variant.unitTest.name.capitalize()}1", SingleOutputTask) {
                outputFolder.set(project.layout.buildDirectory.dir("customCode/${variant.unitTest.name}-1"))
            }
            variant.unitTest.sources.java.addGeneratedSourceDirectory(unitTestTask1, { it.getOutputFolder() })

            def unitTestTask2 = tasks.register("generatedJavaFor${variant.unitTest.name.capitalize()}2", SingleOutputTask) {
                outputFolder.set(project.layout.buildDirectory.dir("customCode/${variant.unitTest.name}-2"))
            }
            variant.unitTest.sources.java.addGeneratedSourceDirectory(unitTestTask2, { it.getOutputFolder() })
        }
    }
}
