#!/bin/bash
WORKSPACE="$(pwd)"

if [[ "$OSTYPE" = "linux"* ]]; then
  PLATFORM="linux-x86_64"
  JDK_HOME="${WORKSPACE}/prebuilts/studio/jdk/jbr-next/linux/bin/"
  PYTHON3_HOME="${WORKSPACE}/prebuilts/python/linux-x86/bin/"
elif [[ "$OSTYPE" = "darwin"* && ("$(arch)" == "x86_64" || "$(arch)" == "i386") ]]; then
  PLATFORM="darwin-x86_64"
  JDK_HOME="${WORKSPACE}/prebuilts/studio/jdk/jbr-next/mac/Contents/Home/bin/"
  PYTHON3_HOME="${WORKSPACE}/prebuilts/python/mac-x86/bin/"
elif [[ "$OSTYPE" = "darwin"* && "$(arch)" == "arm64" ]]; then
  PLATFORM="darwin-arm64"
  JDK_HOME="${WORKSPACE}/prebuilts/studio/jdk/jbr-next/mac-arm64/Contents/Home/bin/"
  PYTHON3_HOME="${WORKSPACE}/prebuilts/python/mac-arm64/bin/"
else
  echo "Unsupported platform: $OSTYPE"
  exit 1
fi

startup_options=("--max_idle_secs=60")
if [[ "${INCREMENTAL_BUILD}" == "true" ]]; then
  # LINT.IfChange(bazel_user_root)
  startup_options+=("--output_user_root=${WORKSPACE}/out2/bazel_user_root")
  startup_options+=("--output_base=${WORKSPACE}/out/bazel_out")
  startup_options+=("--install_base=${WORKSPACE}/out/bazel_install")
  # LINT.ThenChange(/bazel/ci/bazel.py:bazel_user_root)
fi

# Add JDK to the PATH, so rules_jvm_external can find the 'java' binary.
export PATH="${JDK_HOME}:${PYTHON3_HOME}:${PATH}"
BAZELISK="$WORKSPACE/prebuilts/tools/$PLATFORM/bazel/bazelisk"
"$BAZELISK" "${startup_options[@]}" run \
  --config=ci \
  //tools/base/bazel/ci -- $1
