#!/bin/bash
WORKSPACE="$(pwd)"

if [[ "$OSTYPE" = "linux"* ]]; then
  PLATFORM="linux-x86_64"
  JDK_HOME="prebuilts/studio/jdk/jbr-next/linux/bin/"
elif [[ "$OSTYPE" = "darwin"* && ("$(arch)" == "x86_64" || "$(arch)" == "i386") ]]; then
  PLATFORM="darwin-x86_64"
  JDK_HOME="prebuilts/studio/jdk/jbr-next/darwin/bin/"
elif [[ "$OSTYPE" = "darwin"* && "$(arch)" == "arm64" ]]; then
  PLATFORM="darwin-arm64"
  JDK_HOME="prebuilts/studio/jdk/jbr-next/darwin/bin/"
else
  echo "Unsupported platform: $OSTYPE"
  exit 1
fi

# Add JDK to the PATH, so rules_jvm_external can find the 'java' binary.
export PATH="${PATH}:${WORKSPACE}/${JDK_HOME}"
BAZELISK="$WORKSPACE/prebuilts/tools/$PLATFORM/bazel/bazelisk"
"$BAZELISK" --max_idle_secs=60 run //tools/base/bazel/ci -- $1
