/*
 * Copyright (C) 2026 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.android.tools.lint

import com.android.tools.lint.renderer.STYLE_CSS

internal fun getMultiProjectIndexHtml(
  title: String,
  stats: LintStats,
  projects: List<MultiProjectHtmlReporter.ProjectEntry>,
  clientName: String,
  clientRevision: String?,
): String {
  val dateString = java.util.Date().toString()
  val versionString = clientRevision?.let { "$clientName version $it" } ?: clientName

  val sb = StringBuilder()
  for (entry in projects) {
    val path = com.android.utils.XmlUtils.toXmlAttributeValue(entry.path)
    val href = com.android.utils.XmlUtils.toXmlAttributeValue(entry.fileName)
    sb.append("<tr>\n")
    sb.append("<td><a href=\"").append(href).append("\" class=\"text-blue-600 hover:underline\">").append(path).append("</a></td>\n")
    sb.append("<td class=\"text-red-600\">").append(entry.errorCount).append("</td>\n")
    sb.append("<td class=\"text-yellow-600\">").append(entry.warningCount).append("</td>\n")
    sb.append("</tr>\n")
  }
  val projectRows = sb.toString()

  return "<!DOCTYPE html>\n" +
    "<html lang=\"en\">\n" +
    "<head>\n" +
    "<meta charset=\"UTF-8\">\n" +
    "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n" +
    "<title>" +
    title +
    "</title>\n" +
    "<style>\n" +
    STYLE_CSS +
    "\n" +
    "</style>\n" +
    "</head>\n" +
    "<body>\n" +
    "<header>\n" +
    "<div class=\"header-top-row\">\n" +
    "    <div class=\"header-left\">\n" +
    "        <div class=\"header-branding\">\n" +
    "            <h1 class=\"header-title\" id=\"project-name\">" +
    title +
    "</h1>\n" +
    "            <p class=\"header-date\" id=\"report-date\">" +
    dateString +
    "</p>\n" +
    "        </div>\n" +
    "    </div>\n" +
    "    <div class=\"header-stats\">\n" +
    "        <div class=\"stat-item\">\n" +
    "            <span class=\"stat-label\">Total Projects</span>\n" +
    "            <span class=\"stat-value\">" +
    projects.size +
    "</span>\n" +
    "        </div>\n" +
    "        <div class=\"stat-item\">\n" +
    "            <span class=\"stat-label\">Total Errors</span>\n" +
    "            <span class=\"stat-value text-red-600\">" +
    stats.errorCount +
    "</span>\n" +
    "        </div>\n" +
    "        <div class=\"stat-item\">\n" +
    "            <span class=\"stat-label\">Total Warnings</span>\n" +
    "            <span class=\"stat-value text-yellow-600\">" +
    stats.warningCount +
    "</span>\n" +
    "        </div>\n" +
    "        <div class=\"stat-item\">\n" +
    "            <span class=\"stat-label\">Total Hints</span>\n" +
    "            <span class=\"stat-value text-green-600\">" +
    stats.hintCount +
    "</span>\n" +
    "        </div>\n" +
    "    </div>\n" +
    "</div>\n" +
    "</header>\n" +
    "<div class=\"container-custom\">\n" +
    "<main>\n" +
    "    <section id=\"issues-section\">\n" +
    "        <div class=\"table-container\">\n" +
    "            <table id=\"main-table\">\n" +
    "                <thead id=\"table-headers\">\n" +
    "                    <tr>\n" +
    "                        <th class=\"cursor-pointer\">Project</th>\n" +
    "                        <th class=\"cursor-pointer\">Errors</th>\n" +
    "                        <th class=\"cursor-pointer\">Warnings</th>\n" +
    "                    </tr>\n" +
    "                </thead>\n" +
    "                <tbody>\n" +
    projectRows +
    "                </tbody>\n" +
    "            </table>\n" +
    "        </div>\n" +
    "    </section>\n" +
    "</main>\n" +
    "</div>\n" +
    "<footer class=\"mt-8 p-4 text-center text-gray-500 text-xs border-t border-gray-200\">\n" +
    "Generated by <span id=\"lint-version\">" +
    versionString +
    "</span> at <span id=\"footer-date\">" +
    dateString +
    "</span>\n" +
    "</footer>\n" +
    "</body>\n" +
    "</html>\n"
}
