/*
 * Copyright (C) 2020 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.android.tools.bazel.avd;

import java.io.File;

import org.junit.rules.ExternalResource;

/** JUnit rule that calls the executable generated by the avd rule to start and stop an emulator. */
public final class Emulator extends ExternalResource {

    private final String scriptPath;
    private final String port;

    /**
     * Instantiates a rule that starts and stops an emulator created by the avd rule.
     *
     * @param scriptPath Path to the device executable generated by the avd rule.
     * @param port ADB port to start the emulator on.
     */
    public Emulator(String scriptPath, int port) {
        this.scriptPath = scriptPath;
        this.port = String.valueOf(port);
    }

    @Override
    public void before() throws Throwable {
        long startTime = System.currentTimeMillis();
        System.out.println("Starting emulator (" + port + ")");
        exec(scriptPath, port);
        long elapsedTime = (System.currentTimeMillis() - startTime) / 1000;
        System.out.println("Emulator started after " + elapsedTime + " seconds (" + port + ")");
    }

    @Override
    public void after() {
        try {
            System.out.println("Killing emulator (" + port + ")");
            exec(scriptPath, "kill", port);
            System.out.println("Emulator killed ("  + port + ")");
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    private static void exec(String... cmd) throws Exception {
        String testOutputDir = System.getenv("TEST_UNDECLARED_OUTPUTS_DIR");
        ProcessBuilder processBuilder = new ProcessBuilder().command(cmd);

        File outputFile = null;
        if (testOutputDir != null && !testOutputDir.isEmpty()) {
            // If the output directory is specified, redirect stdout and stderr to a log file.
             outputFile = File.createTempFile(
                "emulator_output_", ".log", new File(testOutputDir));
            processBuilder.redirectErrorStream(true); // Merges stderr into stdout
            processBuilder.redirectOutput(outputFile);
        } else {
            // Otherwise, inherit the I/O streams of the current process.
            processBuilder.inheritIO();
        }

        int exitCode = processBuilder.start().waitFor();
        if (exitCode != 0) {
            throw new Exception(String.format(
                "Emulator script exited with code: %d, logFile: %s", exitCode, outputFile));
        }
    }
}
