/*
 * Copyright (C) 2020 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.android.tools.bazel.avd;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.io.Writer;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

import org.junit.rules.ExternalResource;

/** JUnit rule that calls the executable generated by the avd rule to start and stop an emulator. */
public final class Emulator extends ExternalResource {

    private final String scriptPath;
    private final String port;

    /**
     * Instantiates a rule that starts and stops an emulator created by the avd rule.
     *
     * @param scriptPath Path to the device executable generated by the avd rule.
     * @param port ADB port to start the emulator on.
     */
    public Emulator(String scriptPath, int port) {
        this.scriptPath = scriptPath;
        this.port = String.valueOf(port);
    }

    @Override
    public void before() throws Throwable {
        long startTime = System.currentTimeMillis();
        System.out.println("Starting emulator (" + port + ")");
        exec(scriptPath, port);
        long elapsedTime = (System.currentTimeMillis() - startTime) / 1000;
        System.out.println("Emulator started after " + elapsedTime + " seconds (" + port + ")");
    }

    @Override
    public void after() {
        try {
            System.out.println("Killing emulator (" + port + ")");
            exec(scriptPath, "kill", port);
            System.out.println("Emulator killed ("  + port + ")");
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * Executes a command and prefixes each line of its output with a timestamp.
     *
     * @param cmd The command and its arguments to execute.
     * @throws Exception if the command exits with a non-zero status code, or if there's an
     * interruption while waiting for the process to complete.
     */
    private static void exec(String... cmd) throws Exception {
        String testOutputDir = System.getenv("TEST_UNDECLARED_OUTPUTS_DIR");
        File outputFile = null;

        // Determine the output destination: a new log file or standard output.
        if (testOutputDir != null && !testOutputDir.isEmpty()) {
            outputFile = File.createTempFile("emulator_output_", ".log", new File(testOutputDir));
        }

        ProcessBuilder pb = new ProcessBuilder().command(cmd);
        pb.redirectErrorStream(true); // Merge stdout and stderr into a single stream.

        Process process = pb.start();

        try (Writer writer = (outputFile != null)
                ? new PrintWriter(new FileWriter(outputFile))
                : new PrintWriter(System.out)) {

            final DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");

            // A dedicated thread reads the process's output stream. This prevents the
            // process buffer from filling up, which could cause a deadlock.
            Thread readerThread = new Thread(() -> {
                try (BufferedReader reader = new BufferedReader(
                    new InputStreamReader(process.getInputStream()))) {
                    String line;
                    while ((line = reader.readLine()) != null) {
                        String timestamp = LocalDateTime.now().format(formatter);
                        // Write the timestamped line to the designated writer (file or console).
                        writer.write(String.format("[%s] %s%n", timestamp, line));
                        writer.flush();
                    }
                } catch (IOException e) {
                    // This can happen if the process is terminated abruptly. It's generally
                    // safe to ignore as the process is ending anyway.
                }
            });

            readerThread.start();

            try {
                // Wait for the external process to complete.
                int exitCode = process.waitFor();
                if (exitCode != 0) {
                    throw new Exception(
                            String.format(
                                    "Emulator script exited with code: %d, logFile: %s",
                                    exitCode, outputFile));
                }
            } finally {
                // The launcher script exits, but the emulator process it starts continues
                // to run. This keeps the script's stdout stream open, so we must interrupt
                // the reader thread to prevent it from blocking indefinitely.
                readerThread.interrupt();
            }
        } finally {
            // Ensure the process is destroyed if the main thread was interrupted.
            if (process.isAlive()) {
                process.destroyForcibly();
            }
        }
    }
}
