// ATTENTION -- hash value of this file is checked in the corresponding
// integration test. Please make sure any changes you make here are
// backwards compatible.

apply plugin: 'com.android.application'

android {
    namespace = "com.android.tests.basic"
    compileSdkVersion libs.versions.latestCompileSdk.get().toInteger()
    buildToolsVersion = libs.versions.buildToolsVersion.get()

    defaultConfig {
        minSdkVersion libs.versions.supportLibMinSdk.get()
	//noinspection ExpiredTargetSdkVersion
	targetSdkVersion libs.versions.supportLibMinSdk.get()
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
}

def variantCount = 0
def testVariantCount = 0

androidComponents {
    onVariants(selector().all()) { variant ->
        variantCount++
        if (variant.androidTest != null) {
            testVariantCount++
        }
    }
}

dependencies {
    androidTestImplementation "androidx.test:runner:1.4.0-alpha06"
    androidTestImplementation "androidx.test:rules:1.4.0-alpha06"
}

project.afterEvaluate {
    if (variantCount != 2) {
        throw new GradleException("Wrong number of app variants! Expected 2, got $variantCount")
    }

    if (testVariantCount != 1) {
        throw new GradleException("Wrong number of test variants! Expected 1, got $testVariantCount")
    }
}
