apply plugin: 'com.android.application'

android {
    namespace = "com.example.app"
    compileSdkVersion libs.versions.latestCompileSdk.get().toInteger()
    buildToolsVersion = libs.versions.buildToolsVersion.get()


    dynamicFeatures = [':featureA', ':featureB']

    defaultConfig {
        applicationId "android.databinding.instantappwithfeatures"
        minSdkVersion 23
        vectorDrawables.useSupportLibrary = true
    }

    buildFeatures {
        dataBinding = true
    }
}

dependencies {
    implementation "android.arch.core:runtime:1.1.0"
    implementation "androidx.appcompat:appcompat:1.7.0"
    implementation "androidx.constraintlayout:constraintlayout:2.1.4"
    implementation "androidx.lifecycle:lifecycle-runtime:2.6.2"
}
