"""Rules for creating Android Virtual Devices (AVDs)."""

def _avd_impl(ctx):
    """A rule that declares all the files needed to run an Android emulator.

    Targets that depend on this rule can then launch the emulator using
    the script that is generated by this rule.
    """

    # Declare the output directory where the snapshot will be created.
    snapshot_output = ctx.actions.declare_directory(ctx.label.name + "_snapshot")

    # Look for the source.properties file in the system image to get information
    # about the image from.
    source_properties = None
    system_image_files = ctx.attr.image[DefaultInfo].files.to_list()
    for system_image_file in system_image_files:
        if system_image_file.basename == "source.properties":
            source_properties = system_image_file
            break
    if source_properties == None:
        fail("Supplied system image does not contain a source.properties file")

    # Look for the emulator executable.
    emulator = None
    emulator_files = ctx.attr.emulator[DefaultInfo].files.to_list()
    for emulator_file in emulator_files:
        if emulator_file.basename == "emulator":
            emulator = emulator_file
            break
    if emulator == None:
        fail("Emulator executable not found in " + str(ctx.attr.emulator.label))

    # Look for the java executable.
    java_runtime = ctx.toolchains["@bazel_tools//tools/jdk:runtime_toolchain_type"].java_runtime
    java_bin_path = java_runtime.java_executable_exec_path

    launcher = ctx.outputs.executable
    ctx.actions.expand_template(
        template = ctx.file._template,
        output = launcher,
        is_executable = True,
        substitutions = {
            "%avd_name%": ctx.attr.name,
            "%source_properties_path%": source_properties.path,
            "%source_properties_short_path%": source_properties.short_path,
            "%snapshot_dir_path%": snapshot_output.path,
            "%snapshot_dir_short_path%": snapshot_output.short_path,
            "%emulator_path%": emulator.path,
            "%proto_patcher_path%": ctx.file._proto_patcher.path,
            "%proto_patcher_short_path%": ctx.file._proto_patcher.short_path,
            "%java_bin_path%": java_bin_path,
        },
    )

    runfiles = ctx.runfiles(
        files = [launcher] +
                ctx.files.emulator +
                ctx.files.platform +
                ctx.files._platform_tools +
                ctx.files._proto_patcher +
                ctx.files.image +
                java_runtime.files.to_list(),
    )

    # Generates an AVD snapshot by running the AVD's launcher.
    ctx.actions.run(
        inputs = runfiles.files,
        arguments = ["create-snapshot", "5554"],
        outputs = [snapshot_output],
        executable = launcher,
        execution_requirements = {"cpu:2": ""},
        progress_message = "Creating AVD snapshot for " + str(ctx.label),
    )
    runfiles = runfiles.merge(ctx.runfiles(files = [snapshot_output]))

    return [DefaultInfo(runfiles = runfiles)]

_avd = rule(
    implementation = _avd_impl,
    attrs = {
        "_template": attr.label(
            default = "//tools/base/bazel/avd:emulator_launcher.sh.template",
            allow_single_file = True,
        ),
        "emulator": attr.label(
            default = "//prebuilts/studio/sdk:emulator",
        ),
        "_platform_tools": attr.label(
            default = "//prebuilts/studio/sdk:platform-tools",
        ),
        "_proto_patcher": attr.label(
            default = "//tools/base/bazel/avd/snapshot:proto-patcher_deploy.jar",
            allow_single_file = True,
        ),
        "image": attr.label(
            mandatory = True,
        ),
        "platform": attr.label(
            default = "//prebuilts/studio/sdk:platforms/latest",
        ),
    },
    executable = True,
    toolchains = ["@bazel_tools//tools/jdk:runtime_toolchain_type"],
)

def _avd_macro_impl(name, target_compatible_with, **kwargs):
    _avd(
        name = name,
        target_compatible_with = target_compatible_with,
        **kwargs
    )

avd = macro(
    implementation = _avd_macro_impl,
    inherit_attrs = _avd,
    attrs = {
        "target_compatible_with": attr.label_list(mandatory = True),
    },
)
