/*
 * Copyright (C) 2015 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.android.manifmerger

import com.android.SdkConstants
import com.android.manifmerger.MergingReport.MergedManifestKind
import com.android.utils.FileUtils
import com.android.utils.PathUtils
import com.google.common.base.Enums
import com.google.common.collect.ImmutableList
import com.google.common.io.Closeables
import com.google.common.io.Files
import com.google.common.truth.Truth
import java.io.BufferedReader
import java.io.BufferedWriter
import java.io.File
import java.io.FileWriter
import java.io.IOException
import java.io.InputStream
import java.io.InputStreamReader
import java.nio.charset.StandardCharsets
import java.util.Collections
import org.junit.Assert

object ManifestMergerTestUtil {
  /** Delimiter that indicates the test must fail. An XML output and errors are still generated and checked. */
  private const val DELIM_FAILS = "fails"

  /**
   * Delimiter that starts a library XML content. The delimiter name must be in the form `andit will be used as the base for the test file
   * name. Using separate lib names is encouraged since it makes the error output easier to read.`
   */
  private const val DELIM_LIB = "lib"

  /** Delimiter that starts the main manifest XML content. */
  private const val DELIM_MAIN = "main"

  /** Delimiter that starts an overlay XML content. The delimiter must follow the same rules as [.DELIM_LIB] */
  private const val DELIM_OVERLAY = "overlay"

  /** Delimiter that starts a navigation XML content. The delimiter must follow the same rules as [.DELIM_LIB] */
  private const val DELIM_NAVIGATION = "navigation"

  /** Delimiter that starts the resulting XML content, whatever is generated by the merge. */
  private const val DELIM_RESULT = "result"

  /**
   * Delimiter that starts the SdkLog output. The logger prints each entry on its lines, prefixed with E for errors, W for warnings and P
   * for regular printfs.
   */
  private const val DELIM_ERRORS = "errors"

  /**
   * Delimiter for starts a section that declares how to inject an attribute. The section is composed of one or more lines with the syntax:
   * "/node/node|attr-URI attrName=attrValue". This is essentially a pseudo XPath-like expression.
   */
  private const val DELIM_INJECT_ATTR = "inject"

  /**
   * Delimiter for a section that declares how to toggle a ManifMerger option. The section is composed of one or more lines with the syntax:
   * "functionName=false|true".
   */
  private const val DELIM_FEATURES = "features"

  /**
   * Delimiter for a section that declares how to override the package. The section is composed of one line containing the new package name.
   */
  private const val DELIM_PACKAGE = "package"

  /**
   * Delimiter for a section that declares feature-on-feature dependencies. The section is composed of one or more lines line containing a
   * feature name on each line.
   */
  private const val DELIM_DEPENDENCY_FEATURE_NAMES = "featureDeps"

  /**
   * Delimiter for a section that declares the {@Link MergedManifestKind} to request for the result. This section is composed of one line
   * containing the enum name of the merged manifest kind, and defaults to MERGED if it is omitted.
   */
  private const val DELIM_RESULT_KIND = "resultKind"

  /** Delimiter that indicates the resulting manifest is exactly the same as the main one. */
  private const val DELIM_RESULT_SAME_AS_MAIN = "result-same-as-main"

  /**
   * Loads test data for a given test case. The input (main + libs) are stored in temp files. A new destination temp file is created to
   * store the actual result output. The expected result is actually kept in a string.
   *
   * Data File Syntax:
   * * Lines starting with # are ignored (anywhere, as long as # is the first char).
   * * Lines before the first `@delimiter` are ignored.
   * * Empty lines just after the `@delimiter` and before the first &lt; XML line are ignored.
   * * Valid delimiters are `@main` for the XML of the main app manifest.
   * * Following delimiters are `@libXYZ`, read in the order of definition. The name can be anything as long as it starts with "`@lib`".
   *
   * @param testDataDirectory The resource directory name the data file is located in.
   * @param filename The test data filename. If no extension is provided, this will try with .xml or .txt. Must not be null.
   * @param className The simple name of the test class, the manifest files include it in their output.
   * @return A new [TestFiles] instance. Must not be null.
   * @throws Exception when things fail to load properly.
   */
  @JvmStatic
  @Throws(Exception::class)
  fun loadTestData(testDataDirectory: String, filename: String, className: String): TestFiles {
    var resName = "$testDataDirectory/$filename"
    var `is`: InputStream? = null
    var reader: BufferedReader? = null
    var writer: BufferedWriter? = null

    try {
      `is` = ManifestMergerTestUtil::class.java.getResourceAsStream(resName)
      if (`is` == null && !filename.endsWith(".xml")) {
        val resName2 = "$resName.xml"
        `is` = ManifestMergerTestUtil::class.java.getResourceAsStream(resName2)
        if (`is` != null) {
          resName = resName2
        }
      }
      if (`is` == null && !filename.endsWith(".txt")) {
        val resName3 = "$resName.txt"
        `is` = ManifestMergerTestUtil::class.java.getResourceAsStream(resName3)
        if (`is` != null) {
          resName = resName3
        }
      }
      Assert.assertNotNull("Test data file not found for $testDataDirectory/$filename", `is`)

      reader = BufferedReader(InputStreamReader(`is`!!, StandardCharsets.UTF_8))

      val tempDir = Files.createTempDir()
      PathUtils.addRemovePathHook(tempDir.toPath())

      var line: String? = null
      var delimiter: String? = null
      var skipEmpty = true

      var shouldFail = false
      val features = HashMap<String?, Boolean?>()
      var packageOverride: String? = null
      val injectAttributes = HashMap<String?, String?>()
      val expectedResult = StringBuilder()
      val expectedErrors = StringBuilder()
      var mainFile: File? = null
      var actualResultFile: File? = null
      val libFiles = ArrayList<File?>()
      val overlayFiles = ArrayList<File?>()
      val navigationFiles = ArrayList<File>()
      val dependencyFeatureNames = ArrayList<String?>()
      var resultKind = MergedManifestKind.MERGED
      var tempIndex = 0

      while ((reader.readLine().also { line = it }) != null) {
        val currentLine = line!!
        if (skipEmpty && currentLine.trim { it <= ' ' }.isEmpty()) {
          continue
        }
        if (currentLine.isNotEmpty() && currentLine[0] == '#') {
          continue
        }
        if (currentLine.isNotEmpty() && currentLine[0] == '@') {
          delimiter = currentLine.substring(1)

          Assert.assertTrue(
            "Unknown delimiter @" + delimiter + " in " + resName,
            delimiter.startsWith(DELIM_OVERLAY) ||
              delimiter.startsWith(DELIM_LIB) ||
              delimiter.startsWith(DELIM_NAVIGATION) ||
              delimiter == DELIM_MAIN ||
              delimiter == DELIM_RESULT ||
              delimiter == DELIM_ERRORS ||
              delimiter == DELIM_FAILS ||
              delimiter == DELIM_FEATURES ||
              delimiter == DELIM_INJECT_ATTR ||
              delimiter == DELIM_PACKAGE ||
              delimiter == DELIM_DEPENDENCY_FEATURE_NAMES ||
              delimiter == DELIM_RESULT_KIND ||
              delimiter == DELIM_RESULT_SAME_AS_MAIN,
          )

          skipEmpty = true

          if (writer != null) {
            writer.close()
            writer = null
          }

          if (delimiter == DELIM_FAILS) {
            shouldFail = true
          } else if (delimiter == DELIM_RESULT_SAME_AS_MAIN) {
            Truth.assertWithMessage("@main should come before @result-same-as-main").that<File?>(mainFile).isNotNull()
            expectedResult.append(Files.asCharSource(mainFile!!, StandardCharsets.UTF_8).read())
          } else if (
            (delimiter != DELIM_ERRORS) &&
              (delimiter != DELIM_FEATURES) &&
              (delimiter != DELIM_INJECT_ATTR) &&
              (delimiter != DELIM_PACKAGE) &&
              (delimiter != DELIM_DEPENDENCY_FEATURE_NAMES) &&
              (delimiter != DELIM_RESULT_KIND)
          ) {
            val tempFile: File
            if (delimiter.startsWith(DELIM_NAVIGATION)) {
              tempFile = File(tempDir, delimiter.replace("[^a-zA-Z0-9_-]".toRegex(), "") + SdkConstants.DOT_XML)
            } else {
              tempFile =
                File(
                  tempDir,
                  String.format("%1\$s%2\$d_%3\$s.xml", className, tempIndex++, delimiter.replace("[^a-zA-Z0-9_-]".toRegex(), "")),
                )
            }
            tempFile.deleteOnExit()

            if (delimiter.startsWith(DELIM_OVERLAY)) {
              overlayFiles.add(tempFile)
            } else if (delimiter.startsWith(DELIM_LIB)) {
              libFiles.add(tempFile)
            } else if (delimiter.startsWith(DELIM_NAVIGATION)) {
              navigationFiles.add(tempFile)
            } else if (delimiter == DELIM_MAIN) {
              mainFile = tempFile
            } else if (delimiter == DELIM_RESULT) {
              actualResultFile = tempFile
            } else {
              Assert.fail("Unexpected data file delimiter @" + delimiter + " in " + resName)
            }

            if (delimiter != DELIM_RESULT) {
              writer = BufferedWriter(FileWriter(tempFile))
            }
          }

          continue
        }
        if (delimiter != null && skipEmpty && currentLine.isNotEmpty() && currentLine[0] != '#' && currentLine[0] != '@') {
          skipEmpty = false
        }
        if (writer != null) {
          writer.write(currentLine)
          writer.write('\n'.code)
        } else if (DELIM_RESULT == delimiter) {
          expectedResult.append(currentLine).append('\n')
        } else if (DELIM_ERRORS == delimiter) {
          expectedErrors.append(currentLine).append('\n')
        } else if (DELIM_INJECT_ATTR == delimiter) {
          val parts = currentLine.split("=".toRegex()).dropLastWhile { it.isEmpty() }.toTypedArray()
          if (parts.size == 2) {
            injectAttributes[parts[0]] = if ("null" == parts[1]) null else parts[1]
          }
        } else if (DELIM_FEATURES == delimiter) {
          val parts = currentLine.split("=".toRegex()).dropLastWhile { it.isEmpty() }.toTypedArray()
          if (parts.size == 2) {
            features[parts[0]] = parts[1].toBoolean()
          }
        } else if (DELIM_PACKAGE == delimiter) {
          if (packageOverride == null) {
            packageOverride = currentLine
          }
        } else if (DELIM_DEPENDENCY_FEATURE_NAMES == delimiter) {
          val fname = currentLine.trim { it <= ' ' }
          if (fname.isNotEmpty()) {
            dependencyFeatureNames.add(fname)
          }
        } else if (DELIM_RESULT_KIND == delimiter) {
          val kindName = currentLine.trim { it <= ' ' }

          if (kindName.isNotEmpty()) {
            val optKind = Enums.getIfPresent(MergedManifestKind::class.java, kindName)

            if (!optKind.isPresent) {
              Assert.fail("No value of MergedManifestKind has the name '" + kindName + "'")
            }

            resultKind = optKind.get()
          }
        }
      }

      Truth.assertThat<File?>(mainFile).isNotNull()
      Assert.assertNotNull("Missing @" + DELIM_MAIN + " in " + resName, mainFile)
      Truth.assertWithMessage("There should always be an expected result included in the test case.")
        .that(expectedResult.toString())
        .isNotEmpty()

      Collections.sort(libFiles)

      return TestFiles(
        resName,
        shouldFail,
        overlayFiles.toTypedArray(),
        mainFile!!,
        libFiles.toTypedArray(),
        navigationFiles,
        features,
        injectAttributes,
        dependencyFeatureNames,
        packageOverride,
        resultKind,
        actualResultFile,
        expectedResult.toString(),
        expectedErrors.toString(),
      )
    } finally {
      Closeables.closeQuietly(reader)
      Closeables.closeQuietly(`is`)
      if (writer != null) {
        writer.close()
      }
    }
  }

  @JvmStatic
  fun transformParameters(params: Array<String?>): MutableCollection<Array<Any?>?> {
    return params.map { arrayOf<Any?>(it) }.toMutableList()
  }

  class TestFiles(
    val testDataRelativePath: String,
    val shouldFail: Boolean,
    val overlayFiles: Array<File?>,
    val main: File,
    val libs: Array<File?>,
    navigationFiles: Iterable<File>,
    val features: MutableMap<String?, Boolean?>,
    val injectAttributes: MutableMap<String?, String?>,
    val dependencyFeatureNames: List<String?>,
    val packageOverride: String?,
    val resultKind: MergedManifestKind,
    val actualResult: File?,
    val expectedResult: String,
    val expectedErrors: String,
  ) {
    val navigationFiles: List<File> = ImmutableList.copyOf<File>(navigationFiles)

    // Try to delete any temp file potentially created.
    fun cleanup() {
      try {
        if (main.isFile) {
          FileUtils.delete(main)
        }

        if (actualResult != null && actualResult.isFile) {
          FileUtils.delete(actualResult)
        }

        for (f in libs) {
          if (f != null && f.isFile) {
            FileUtils.delete(f)
          }
        }
      } catch (e: IOException) {
        throw AssertionError(e)
      }
    }
  }
}
