package com.example.bytecode.plugins;

import com.android.build.api.artifact.MultipleArtifact;
import com.android.build.api.artifact.ScopedArtifact;
import com.android.build.api.variant.ApplicationAndroidComponentsExtension;
import com.android.build.api.variant.Component;
import com.android.build.api.variant.LibraryAndroidComponentsExtension;
import com.android.build.api.variant.ScopedArtifacts;
import com.android.build.api.variant.TestAndroidComponentsExtension;
import java.io.File;
import org.gradle.api.Plugin;
import org.gradle.api.Project;
import org.gradle.api.tasks.TaskProvider;

/**
 * Simple plugin that register a bytecode generating task
 *
 * <p>It loops on all the variants (including the test ones), and for each variant it registers a
 * new task. The bytecode generated by the task depends on the type of the variant (app vs lib vs
 * test)
 */
public class CompilerPlugin implements Plugin<Project> {

    private Project project;
    private File appJar;
    private File postJavacAppJar;
    private File libJar;
    private File postJavacLibJar;
    private File testJar;

    @Override
    public void apply(Project project) {
        this.project = project;

        computeJarLocations();

        ApplicationAndroidComponentsExtension appComponents =
                project.getExtensions().findByType(ApplicationAndroidComponentsExtension.class);
        if (appComponents != null) {
            appComponents.onVariants(
                    appComponents.selector().all(),
                    variant -> {
                        processVariant(variant, appJar, postJavacAppJar);
                        if (variant.getUnitTest() != null) {
                            processVariant(variant.getUnitTest(), testJar, null);
                        }
                        if (variant.getAndroidTest() != null) {
                            processVariant(variant.getAndroidTest(), testJar, null);
                        }
                    });
        }

        LibraryAndroidComponentsExtension libComponents =
                project.getExtensions().findByType(LibraryAndroidComponentsExtension.class);
        if (libComponents != null) {
            libComponents.onVariants(
                    libComponents.selector().all(),
                    variant -> {
                        processVariant(variant, libJar, postJavacLibJar);
                        if (variant.getUnitTest() != null) {
                            processVariant(variant.getUnitTest(), testJar, null);
                        }
                        if (variant.getAndroidTest() != null) {
                            processVariant(variant.getAndroidTest(), testJar, null);
                        }
                    });
        }

        TestAndroidComponentsExtension testComponents =
                project.getExtensions().findByType(TestAndroidComponentsExtension.class);
        if (testComponents != null) {
            testComponents.onVariants(
                    testComponents.selector().all(),
                    variant -> {
                        processVariant(variant, testJar, null);
                    });
        }
    }

    private void computeJarLocations() {
        File rootDir = project.getRootProject().getProjectDir();
        appJar = new File(rootDir, "app.jar");
        postJavacAppJar = new File(rootDir, "postjavacapp.jar");
        libJar = new File(rootDir, "lib.jar");
        postJavacLibJar = new File(rootDir, "postjavaclib.jar");
        testJar = new File(rootDir, "test.jar");
    }

    private void processVariant(Component variant, File sourceJar, File postJavacJar) {
        // Source folders
        if (postJavacJar != null && variant.getSources().getJava() != null) {
            variant.getSources().getJava().addStaticSourceDirectory("src/custom/java");
        }

        // Output the source folders.
        try {
            if (variant.getSources().getJava() != null) {
                variant.getSources()
                        .getJava()
                        .getAll()
                        .get()
                        .forEach(
                                dir -> {
                                    System.out.println(
                                            "SourceFoldersApi("
                                                    + project.getPath()
                                                    + ":"
                                                    + variant.getName()
                                                    + "): "
                                                    + dir.getAsFile());
                                });
            }
        } catch (Exception e) {
            // ignore
        }

        // Pre-javac bytecode generation
        TaskProvider<BytecodeGeneratingTask> t =
                project.getTasks()
                        .register(
                                "generateBytecodeFor" + variant.getName(),
                                BytecodeGeneratingTask.class,
                                task -> {
                                    task.setSourceJar(sourceJar);
                                    task.setClasspath(variant.getCompileClasspath());
                                });

        // Add to PRE_COMPILATION_CLASSES so javac can see it
        variant.getArtifacts()
                .use(t)
                .wiredWith(task -> task.getOutputDirProperty())
                .toAppendTo(MultipleArtifact.PRE_COMPILATION_CLASSES.INSTANCE);

        // Also add to final classes for dexing
        variant.getArtifacts()
                .forScope(ScopedArtifacts.Scope.PROJECT)
                .use(t)
                .toAppend(ScopedArtifact.CLASSES.INSTANCE, task -> task.getOutputDirProperty());

        // Also add to JAVA_RES to include META-INF files
        variant.getArtifacts()
                .forScope(ScopedArtifacts.Scope.PROJECT)
                .use(t)
                .toAppend(ScopedArtifact.JAVA_RES.INSTANCE, task -> task.getOutputDirProperty());

        // Post-javac bytecode generation
        if (postJavacJar != null) {
            TaskProvider<BytecodeGeneratingTask> t2 =
                    project.getTasks()
                            .register(
                                    "generateBytecode2For" + variant.getName(),
                                    BytecodeGeneratingTask.class,
                                    task -> {
                                        task.setSourceJar(postJavacJar);
                                        task.setClasspath(variant.getCompileClasspath());
                                    });

            variant.getArtifacts()
                    .forScope(ScopedArtifacts.Scope.PROJECT)
                    .use(t2)
                    .toAppend(ScopedArtifact.CLASSES.INSTANCE, task -> task.getOutputDirProperty());

            variant.getArtifacts()
                    .forScope(ScopedArtifacts.Scope.PROJECT)
                    .use(t2)
                    .toAppend(ScopedArtifact.JAVA_RES.INSTANCE, task -> task.getOutputDirProperty());
        }
    }
}
