load("//tools/base/bazel:gradle.bzl", "gradle_build")
load("//tools/base/bazel:maven.bzl", "maven_repository")
load("//tools/base/bazel:utils.bzl", "merged_zip")
load("//tools/base/build-system:hybrid_build.bzl", "GRADLE_PROPERTIES")

filegroup(
    name = "agp_gradle_build_files",
    srcs = ["build.gradle"],
)

# keep sorted
UTP_SOURCE_FILES = [
    ":agp_gradle_build_files",
    "//tools:agp_gradle_build_files",
    "//tools/base/common:agp_gradle_build_files",
    "//tools/base/utp/android-device-provider-ddmlib:agp_gradle_build_files",
    "//tools/base/utp/android-device-provider-profile:agp_gradle_build_files",
    "//tools/base/utp/android-test-plugin-host-additional-test-output:agp_gradle_build_files",
    "//tools/base/utp/android-test-plugin-host-apk-installer:agp_gradle_build_files",
    "//tools/base/utp/android-test-plugin-host-coverage:agp_gradle_build_files",
    "//tools/base/utp/android-test-plugin-host-device-info:agp_gradle_build_files",
    "//tools/base/utp/android-test-plugin-host-emulator-control:agp_gradle_build_files",
    "//tools/base/utp/android-test-plugin-host-logcat:agp_gradle_build_files",
    "//tools/base/utp/android-test-plugin-result-listener-gradle:agp_gradle_build_files",
    "//tools/base/utp/gradle-work-action:agp_gradle_build_files",
    "//tools/base/utp/gradle-work-action-api:agp_gradle_build_files",
    "//tools/base/utp/utp-common:agp_gradle_build_files",
    "//tools/buildSrc:agp_gradle_build_files",
    "//tools/buildSrc/base:agp_gradle_build_files",
]

maven_repository(
    name = "utp_dependencies",
    # keep sorted
    artifacts = [
        "//tools/base/common:tools.common",
        "//tools/base/ddmlib:tools.ddmlib",
        "//tools/base/emulator/proto",
        "//tools/base/sdk-common:tools.sdk-common",
        "//tools/base/sdklib:tools.sdklib",
        "//tools/base/utp/android-device-provider-ddmlib-proto",
        "//tools/base/utp/android-device-provider-profile-proto",
        "//tools/base/utp/android-test-plugin-host-additional-test-output-proto",
        "//tools/base/utp/android-test-plugin-host-apk-installer-proto",
        "//tools/base/utp/android-test-plugin-host-coverage-proto",
        "//tools/base/utp/android-test-plugin-host-device-info-proto",
        "//tools/base/utp/android-test-plugin-host-emulator-control-proto",
        "//tools/base/utp/android-test-plugin-host-logcat-proto",
        "//tools/base/utp/android-test-plugin-result-listener-gradle-proto",
        "@maven//:com.google.testing.compile.compile-testing",
        "@maven//:com.google.testing.platform.android-device-provider-local",
        "@maven//:com.google.testing.platform.android-driver-instrumentation",
        "@maven//:com.google.testing.platform.android-test-plugin",
        "@maven//:com.google.testing.platform.core",
        "@maven//:com.google.testing.platform.core-proto",
        "@maven//:com.google.testing.platform.launcher",
    ],
)

gradle_build(
    name = "utp",
    build_file = "//tools:agp_gradle_build_root_build_file",
    data = ["//prebuilts/studio/jdk/jdk11:jdk_runtime_files"] + UTP_SOURCE_FILES,
    gradle_properties = GRADLE_PROPERTIES,
    output_file = "utp.zip",
    output_file_source = "dist/repo.zip",
    repos = [
        ":utp_dependencies",
        "//tools/base:agp_dependencies",
    ],
    tasks = [":base:utp:zipUtp"],
    visibility = [
        "//tools/base/gmaven:__pkg__",
    ],
)

merged_zip(
    name = "utp_maven_repo_for_integration_tests",
    testonly = 1,
    srcs = [
        ":utp.zip",
        ":utp_dependencies.zip",
    ],
    visibility = [
        "//tools/base/build-system/integration-test:__subpackages__",
        "//tools/vendor/google/android-ndk:__subpackages__",
        "//tools/vendor/google/lldb-integration-tests:__subpackages__",
    ],
)
