load("//tools/base/bazel:maven.bzl", "maven_repository")
load("//tools/base/bazel:utils.bzl", "merged_zip")

maven_repository(
    name = "utp_dependencies",
    # keep sorted
    artifacts = [
        "//tools/base/android-test/android-test-engine-result-listener:android-test-engine-result-listener",
        "//tools/base/android-test/android-test-engine-result-listener:test_result_event_proto",
        "//tools/base/android-test/android-test-junit-engine:android-test-engine",
        "//tools/base/android-test/test-result-proto:test-result-proto",
        "//tools/base/common:tools.common",
        "//tools/base/ddmlib:tools.ddmlib",
        "//tools/base/sdk-common:tools.sdk-common",
        "//tools/base/sdklib:tools.sdklib",
        "@maven//:org.junit.platform.junit-platform-engine",
        "@maven//:org.junit.platform.junit-platform-launcher",
    ],
)

maven_repository(
    name = "utp",
    artifacts = [
        "//tools/base/utp/gradle-work-action",
    ],
    include_transitive_deps = False,
    visibility = [
        "//tools/base/gmaven:__pkg__",
    ],
)

merged_zip(
    name = "utp_maven_repo_for_integration_tests",
    testonly = 1,
    srcs = [
        ":utp.zip",
        ":utp_dependencies.zip",
    ],
    visibility = [
        "//tools/base/build-system/integration-test:__subpackages__",
        "//tools/vendor/google/android-ndk:__subpackages__",
        "//tools/vendor/google/lldb-integration-tests:__subpackages__",
        "//tools/vendor/google/ml:__subpackages__",
    ],
)
