apply from: "../commonHeader.gradle"
buildscript { apply from: "../commonBuildScript.gradle" }

apply plugin: 'com.android.application'

android {
    namespace = "com.example.SanAngeles"
    compileSdkVersion libs.versions.latestCompileSdk.get().toInteger()
    buildToolsVersion = libs.versions.buildToolsVersion.get()

    defaultConfig {
        minSdkVersion libs.versions.ndk19SupportLibMinSdk.get()
        ndk {
            moduleName = "sanangeles"
            cFlags = "-DANDROID_NDK -DDISABLE_IMPORTGL"
            ldLibs "GLESv1_CM", "dl", "log"
            stl = "stlport_static"
            jobs = 4
        }

        // This actual the app version code. Giving ourselves 1,000,000 values
        versionCode = 123
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes.debug.jniDebuggable true
    externalNativeBuild {
        ndkBuild {
            path "Android.mk"
        }
    }
    splits {
        abi {
            enable = true
            reset()
            include 'x86', 'armeabi-v7a'
            universalApk = true
        }
    }
}

// map for the version code.
ext.versionCodes = ['armeabi-v7a':1, x86:2]

androidComponents {
    onVariants(selector().all()) { variant ->
        variant.outputs.forEach { output ->
            println("Customizing " + output)
	    def value
	    def filter = output.getFilter(com.android.build.api.variant.FilterConfiguration.FilterType.ABI)
	    if (filter == null) {
	        value = 3
	    }
	    else {
	        value = project.ext.versionCodes.get(filter.identifier)
	    }
	    output.versionCode.set(output.versionCode.get() + (value * 1000000))
        }
    }
}

dependencies {
    testImplementation 'junit:junit:4.12'
    androidTestImplementation "androidx.test:runner:1.4.0-alpha06"
    androidTestImplementation "androidx.test:rules:1.4.0-alpha06"
}
