apply from: "../commonHeader.gradle"
buildscript { apply from: "../commonBuildScript.gradle" }

apply plugin: 'com.android.application'

android {
    namespace = "com.android.tests.basic"
    compileSdkVersion libs.versions.latestCompileSdk.get().toInteger()
    buildToolsVersion = libs.versions.buildToolsVersion.get()

    defaultConfig {
        minSdkVersion libs.versions.supportLibMinSdk.get()
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    packagingOptions {
        exclude 'excluded.txt'
        pickFirst 'first_pick.txt'
        merge 'merge.txt'

        pickFirst 'lib/x86/libdummy.so'
    }
}

dependencies {
    api files('jar1.jar')
    api files('jar2.jar')

    androidTestImplementation "androidx.test:runner:1.4.0-alpha06"
    androidTestImplementation "androidx.test:rules:1.4.0-alpha06"
}
