{
  "formatVersion": "1.1",
  "component": {
    "url": "../../tracing/2.0.0-SNAPSHOT/tracing-2.0.0-SNAPSHOT.module",
    "group": "androidx.tracing",
    "module": "tracing",
    "version": "2.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1",
      "buildId:": "14746442"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.tracing",
          "module": "tracing-ktx",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          },
          "reason": "tracing is in atomic group androidx.tracing"
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-wire",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          },
          "reason": "tracing is in atomic group androidx.tracing"
        }
      ],
      "files": [
        {
          "name": "tracing-desktop-2.0.0-SNAPSHOT.jar",
          "url": "tracing-desktop-2.0.0-SNAPSHOT.jar",
          "size": 115020,
          "sha512": "0c902064fa4f3f71168ec5e58580381cbadfbc8821497c25103e4ad73c4256eff365292ff569d664339f48b26c024b33e06460d8c4f6da4494c428fdef85c3db",
          "sha256": "db53442d64d1ba44fa5dd7eed2bd76c47df7f7628e00ea20e9a316fdc35d2f5e",
          "sha1": "9d9c2d5463230f47acfcc471d30c43b693f30254",
          "md5": "bdede74754307fbc9ab82f216c0a55cd"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.4.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.tracing",
          "module": "tracing-ktx",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          },
          "reason": "tracing is in atomic group androidx.tracing"
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-wire",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          },
          "reason": "tracing is in atomic group androidx.tracing"
        }
      ],
      "files": [
        {
          "name": "tracing-desktop-2.0.0-SNAPSHOT.jar",
          "url": "tracing-desktop-2.0.0-SNAPSHOT.jar",
          "size": 115020,
          "sha512": "0c902064fa4f3f71168ec5e58580381cbadfbc8821497c25103e4ad73c4256eff365292ff569d664339f48b26c024b33e06460d8c4f6da4494c428fdef85c3db",
          "sha256": "db53442d64d1ba44fa5dd7eed2bd76c47df7f7628e00ea20e9a316fdc35d2f5e",
          "sha1": "9d9c2d5463230f47acfcc471d30c43b693f30254",
          "md5": "bdede74754307fbc9ab82f216c0a55cd"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.tracing",
          "module": "tracing-ktx",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          },
          "reason": "tracing is in atomic group androidx.tracing"
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-wire",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          },
          "reason": "tracing is in atomic group androidx.tracing"
        }
      ],
      "files": [
        {
          "name": "tracing-desktop-2.0.0-SNAPSHOT-sources.jar",
          "url": "tracing-desktop-2.0.0-SNAPSHOT-sources.jar",
          "size": 56924,
          "sha512": "05b81c064c09bca4331b8b572db700c7679d6b79b52427d113447318d150c1701a51740945d79fee9ca6c14805b6e69ab1a8c5cd3d69e0ca02cee542e4764994",
          "sha256": "ed84eb191d1f9125f6eee48f64fed5f6f2e55adbdae34508ff1137de0c3fc85f",
          "sha1": "9c67916296e7fad56e8cd39254653bacf68925f2",
          "md5": "2b974ddb1e5a74c65c1b534c7539c671"
        }
      ]
    }
  ]
}