apply plugin: 'com.android.test'

android {
    namespace = "com.android.tests.basic.test"
    compileSdkVersion libs.versions.latestCompileSdk.get().toInteger()
    buildToolsVersion = libs.versions.buildToolsVersion.get()

    targetProjectPath ':app'
    buildTypes {
        create("minified").initWith(buildTypes.debug)
        minified {
            minifyEnabled true
            testProguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    defaultConfig {
        minSdkVersion libs.versions.supportLibMinSdk.get()
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
}

dependencies {
    implementation 'junit:junit:4.12'
    implementation "androidx.test:runner:1.4.0-alpha06"
    implementation "androidx.test:rules:1.4.0-alpha06"
    implementation "androidx.annotation:annotation-experimental:1.3.0"
}
