macos_sdk_repository = use_repo_rule("//build/bazel/toolchains/cc:repository_rules.bzl", "macos_sdk_repository")

msvc_tools_repository = use_repo_rule("//build/bazel/toolchains/cc:repository_rules.bzl", "msvc_tools_repository")

windows_sdk_repository = use_repo_rule("//build/bazel/toolchains/cc:repository_rules.bzl", "windows_sdk_repository")

local_repository = use_repo_rule("@bazel_tools//tools/build_defs/repo:local.bzl", "local_repository")

rbe = use_extension("//tools/base/bazel/rbe:extensions.bzl", "rbe")

macos_sdk_repository(
    name = "macos_sdk",
    build_file = "//build/bazel/toolchains/cc/mac_clang:sdk.BUILD",
)

msvc_tools_repository(
    name = "vctools",
    build_file = "//build/bazel/toolchains/cc/windows_clang:vctools.BUILD",
)

windows_sdk_repository(
    name = "windows_sdk",
    build_file_template = "//build/bazel/toolchains/cc/windows_clang:sdk.BUILD.tpl",
    sdk_path = "C:\\Program Files (x86)\\Windows Kits\\10",
)

local_repository(
    name = "windows_toolchains",
    path = "tools/base/bazel/toolchains/windows",
)

# CC toolchains
register_toolchains(
    "@native_toolchain//:cc-toolchain-x64_linux",
    "@native_toolchain//:cc-toolchain-darwin",
    "@native_toolchain//:cc-toolchain-x64_windows-clang-cl",
    "//build/bazel/toolchains/cc/linux_clang:x64_toolchain",
    "//build/bazel/toolchains/cc/mac_clang:x64_toolchain",
    "//build/bazel/toolchains/cc/mac_clang:arm64_toolchain",
    "//build/bazel/toolchains/cc/windows_clang:x64_toolchain",
)

# Python toolchains
register_toolchains(
    "//tools/base/bazel/toolchains/darwin:python_toolchain",
    "//prebuilts/python/linux-x86:python_toolchain",
    # Bazel cannot auto-detect python on Windows yet
    # See: https://github.com/bazelbuild/bazel/issues/7844
    "@windows_toolchains//:python_toolchain",
)

# Java toolchains
register_toolchains(
    # Java runtime for executing tests and binaries ('java')
    "//prebuilts/studio/jdk/jdk11:runtime_toolchain_definition",
    "//prebuilts/studio/jdk/jdk17:runtime_toolchain_definition",
    "//prebuilts/studio/jdk/jbr-next:runtime_toolchain_definition",

    # Java runtime used to execute the Java compiler ('javac')
    "//prebuilts/studio/jdk:java8_compile_toolchain_definition",
    "//prebuilts/studio/jdk:java11_compile_toolchain_definition",
    "//prebuilts/studio/jdk:java17_compile_toolchain_definition",
    "//prebuilts/studio/jdk:java21_compile_toolchain_definition",

    # Bazel want those for bootclasspath shenanigans. Not used in studio-main rules
    # https://github.com/bazelbuild/rules_java/blob/master/toolchains/BUILD#L75
    "//prebuilts/studio/jdk/jdk17:bootstrap_runtime_toolchain_definition",
    "//prebuilts/studio/jdk/jbr-next:bootstrap_runtime_toolchain_definition",
)

rbe.constant(
    name = "LARGE_MACHINE",
    labels = {
        "machine-size": "large",
    },
)
use_repo(rbe, "exec_properties")
