load("//tools/base/bazel:kotlin.bzl", "kotlin_test")

kotlin_test(
    name = "integration-test",
    srcs = glob([
        "java/**/*.kt",
        "java/**/*.java",
    ]),
    data = [
        "//tools/base/sdklib:commandlinetools",
    ],
    jvm_flags = ["-Dtest.suite.jar=integration-test.jar"],
    tags = [
        "ci:studio-mac",
        "ci:studio-mac-arm",
        "cpu:1",
    ],
    test_class = "com.android.testutils.JarTestSuite",
    visibility = ["//tools/base/sdklib:__pkg__"],
    deps = [
        "//tools/base/annotations",
        "//tools/base/testutils:tools.testutils",
        "@maven//:com.google.truth.truth",
        "@maven//:junit.junit",
    ],
)
