/*
 * Copyright (C) 2021 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.android.tools.deploy.liveedit;

import com.android.annotations.NonNull;
import com.android.deploy.asm.Type;
import com.android.tools.deploy.interpreter.FieldDescription;
import com.android.tools.deploy.interpreter.MethodDescription;
import com.android.tools.deploy.interpreter.ObjectValue;
import com.android.tools.deploy.interpreter.Value;

import java.lang.reflect.Method;
import java.util.HashMap;
import java.util.List;

/**
 * Evaluator that handles method access, field access, and type casting for proxy classes.
 *
 * <p>Note: when resolving methods of proxy classes, this class will call the bytecode
 * implementation directly rather than going via the proxy interface of the object. This allows
 * handling added methods that are *not* part of the proxy interface.
 *
 * <p>For proxy interfaces generated by {@link java.lang.reflect.Proxy}, this is any method that
 * isn't implementing an interface.
 *
 * <p>For proxy interfaces in {@link com.android.tools.deploy.liveedit.proxies.Proxies}, this
 * includes any method that isn't implementing an interface *or* overriding a method of a supertype.
 */
class ProxyClassEval extends AndroidEval {
    private static final HashMap<Type, Class<?>> primitiveToClass = new HashMap<>();

    static {
        primitiveToClass.put(Type.BOOLEAN_TYPE, boolean.class);
        primitiveToClass.put(Type.BYTE_TYPE, byte.class);
        primitiveToClass.put(Type.CHAR_TYPE, char.class);
        primitiveToClass.put(Type.SHORT_TYPE, short.class);
        primitiveToClass.put(Type.INT_TYPE, int.class);
        primitiveToClass.put(Type.LONG_TYPE, long.class);
        primitiveToClass.put(Type.FLOAT_TYPE, float.class);
        primitiveToClass.put(Type.DOUBLE_TYPE, double.class);
    }

    private final LiveEditContext context;

    public ProxyClassEval(LiveEditContext context) {
        super(context.getClassLoader());
        this.context = context;
    }

    @NonNull
    @Override
    public Value getField(@NonNull Value target, FieldDescription field) {
        if (target.obj() instanceof ProxyClass) {
            InterpreterLogger.v("(proxy) getField: " + field);
            ProxyClass proxy = (ProxyClass) target.obj();
            return makeValue(
                    proxy.getHandler().getField(field.getName()), Type.getType(field.getDesc()));
        }

        return super.getField(target, field);
    }

    @Override
    public void setField(@NonNull Value target, FieldDescription field, Value value) {
        if (target.obj() instanceof ProxyClass) {
            InterpreterLogger.v("(proxy) setField: " + field);
            ProxyClass proxy = (ProxyClass) target.obj();
            proxy.getHandler().setField(field.getName(), value.obj());
        } else {
            super.setField(target, field, value);
        }
    }

    @NonNull
    @Override
    public Value getStaticField(FieldDescription field) {
        LiveEditClass clazz = context.getClass(field.getOwnerInternalName());
        if (clazz != null && clazz.isProxyClass()) {
            InterpreterLogger.v("(proxy) getStaticField: " + field);
            Object value = clazz.getStaticField(field.getName());
            InterpreterLogger.v("        \tfield_type=" + value.getClass());
            return makeValue(value, Type.getType(field.getDesc()));
        }

        return super.getStaticField(field);
    }

    @Override
    public void setStaticField(FieldDescription field, @NonNull Value value) {
        LiveEditClass clazz = context.getClass(field.getOwnerInternalName());
        if (clazz != null && clazz.isProxyClass()) {
            InterpreterLogger.v("(proxy) setStaticField: " + field);
            clazz.setStaticField(field.getName(), value.obj());
            InterpreterLogger.v("        \tfield_type=" + value.obj().getClass());
        } else {
            super.setStaticField(field, value);
        }
    }

    @NonNull
    @Override
    public Value invokeSpecial(
            @NonNull Value target,
            MethodDescription method,
            @NonNull List<? extends Value> argsValues) {
        final String ownerInternalName = method.getOwnerInternalName();
        final String methodName = method.getName();
        final String methodDesc = method.getDesc();

        if (method.isConstructor()) {
            // We're calling a super() constructor.
            if (target.obj() instanceof ProxyClass) {
                InterpreterLogger.v("(proxy) invokeSpecial [super]: " + method);
                ProxyClassHandler handler = ((ProxyClass) target.obj()).getHandler();

                Type[] argTypes = Type.getArgumentTypes(methodDesc);
                Class<?>[] types = new Class<?>[argsValues.size()];
                Object[] args = new Object[argsValues.size()];
                for (int i = 0; i < argTypes.length; ++i) {
                    try {
                        types[i] = typeToClass(argTypes[i]);
                    } catch (ClassNotFoundException e) {
                        throw new LiveEditException("Could not resolve super() arg type", e);
                    }
                    args[i] = argsValues.get(i).obj();
                }
                handler.superInit(types, args);
                return Value.VOID_VALUE;
            }

            // If we're calling the constructor of a proxied class, set up a new proxy instance.
            LiveEditClass clazz = context.getClass(ownerInternalName);
            if (clazz != null && clazz.isProxyClass()) {
                InterpreterLogger.v("(proxy) invokeSpecial [init]: " + method);

                ObjectValue objTarget = (ObjectValue) target;
                ProxyClass instance = clazz.createProxyInstance();
                instance.getHandler()
                        .invokeMethod(
                                instance, "<init>", methodDesc, valueToObj(argsValues, methodDesc));

                // If we have a special generated type to serve as the proxy interface, replace the
                // VM-generated proxy interface with our own custom one.
                Object superInstance = instance.getHandler().getSuperInstance();
                if (superInstance instanceof ProxyClass) {
                    objTarget.setValue(superInstance);
                    ((ProxyClass) superInstance).setHandler(instance.getHandler());
                } else {
                    objTarget.setValue(instance);
                }
                return Value.VOID_VALUE;
            }
        } else if (target.obj() instanceof ProxyClass) {
            InterpreterLogger.v("(proxy) invokeSpecial: " + method);
            ProxyClass proxy = (ProxyClass) target.obj();
            Object result =
                    proxy.getHandler()
                            .invokeMethod(
                                    proxy,
                                    methodName,
                                    methodDesc,
                                    valueToObj(argsValues, methodDesc));
            return makeValue(result, Type.getReturnType(methodDesc));
        }

        return super.invokeSpecial(target, method, argsValues);
    }

    @NonNull
    @Override
    public Value invokeInterface(
            @NonNull Value target, MethodDescription method, @NonNull List<? extends Value> args) {
        final String methodName = method.getName();
        final String methodDesc = method.getDesc();

        if (target.obj() instanceof ProxyClass) {
            InterpreterLogger.v("(proxy) invokeInterface: " + method);
            ProxyClass proxy = (ProxyClass) target.obj();
            Object result =
                    proxy.getHandler()
                            .invokeMethod(
                                    proxy, methodName, methodDesc, valueToObj(args, methodDesc));
            return makeValue(result, Type.getReturnType(methodDesc));
        }

        return super.invokeInterface(target, method, args);
    }

    @NonNull
    @Override
    public Value invokeMethod(
            @NonNull Value target, MethodDescription method, @NonNull List<? extends Value> args) {
        final String methodName = method.getName();
        final String methodDesc = method.getDesc();

        if (target.obj() instanceof ProxyClass) {
            InterpreterLogger.v("(proxy) invokeMethod: " + method);
            ProxyClass proxy = (ProxyClass) target.obj();
            Object result =
                    proxy.getHandler()
                            .invokeMethod(
                                    proxy, methodName, methodDesc, valueToObj(args, methodDesc));
            return makeValue(result, Type.getReturnType(methodDesc));
        }

        return super.invokeMethod(target, method, args);
    }

    @NonNull
    @Override
    public Value invokeStaticMethod(MethodDescription method, @NonNull List<? extends Value> args) {
        final String internalName = method.getOwnerInternalName();
        final String methodName = method.getName();
        final String methodDesc = method.getDesc();

        LiveEditClass clazz = context.getClass(internalName);
        if (clazz == null) {
            return super.invokeStaticMethod(method, args);
        }

        // We interpret *all* static methods of proxy classes.
        if (clazz.isProxyClass()) {
            InterpreterLogger.v("(proxy) invokeStaticMethod: " + method);
            Object result =
                    clazz.invokeDeclaredMethod(
                            methodName, methodDesc, null, valueToObj(args, methodDesc));
            return makeValue(result, Type.getReturnType(methodDesc));
        }

        try {
            // If the method is a synthetic static added by Compose compiler, we must interpret it.
            // To detect these methods, we check if a given static method exists in the original.
            Type[] parameterTypes = Type.getArgumentTypes(methodDesc);
            Type returnType = Type.getReturnType(methodDesc);
            Method originalMethod =
                    methodLookup(internalName, methodName, parameterTypes, returnType);
            if (originalMethod == null) {
                InterpreterLogger.v("(proxy) invokeStaticMethod: " + method);
                Object result =
                        clazz.invokeDeclaredMethod(
                                methodName, methodDesc, null, valueToObj(args, methodDesc));
                return makeValue(result, Type.getReturnType(methodDesc));
            }
        } catch (ClassNotFoundException cnfe) {
            // Ignore; let AndroidEval handle it.
        }

        return super.invokeStaticMethod(method, args);
    }

    @Override
    public boolean isInstanceOf(@NonNull Value target, @NonNull Type type) {
        if (target.obj() instanceof ProxyClass) {
            ProxyClass proxy = (ProxyClass) target.obj();
            return proxy.getHandler().isInstanceOf(type);
        }
        return super.isInstanceOf(target, type);
    }

    private static Object[] valueToObj(List<? extends Value> args, String methodDesc) {
        Type[] argTypes = Type.getArgumentTypes(methodDesc);
        Object[] argValues = new Object[args.size()];
        for (int i = 0; i < argValues.length; i++) {
            argValues[i] = args.get(i).obj(argTypes[i]);
        }
        return argValues;
    }
}
