load("//tools/base/bazel:bazel.bzl", "iml_module")
load("//tools/base/bazel:kotlin.bzl", "kotlin_library")

# managed by go/iml_to_build
iml_module(
    name = "studio.android.sdktools.testlib",
    enable_tests = False,
    iml_files = ["android.sdktools.testlib.iml"],
    test_srcs = ["testSrc"],
    visibility = ["//visibility:public"],
    deps = ["@intellij//:intellij-sdk"],
)

kotlin_library(
    name = "testlib",
    srcs = glob([
        "testSrc/**/*.java",
        "testSrc/**/*.kt",
    ]),
    visibility = ["//visibility:public"],
)
