apply plugin: 'com.android.test'
apply plugin: 'com.example.compiler'

android {
    namespace = "com.android.tests.basic.test"
    compileSdk = libs.versions.latestCompileSdk.get().toInteger()
    buildToolsVersion = libs.versions.buildToolsVersion.get()
    defaultConfig {
        minSdk = libs.versions.supportLibMinSdk.get().toInteger()
        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    targetProjectPath = ':app'
}

dependencies {
    implementation 'junit:junit:4.12'
    implementation "androidx.test:runner:1.4.0-alpha06"
    implementation "androidx.test:rules:1.4.0-alpha06"
    implementation "androidx.annotation:annotation-experimental:1.3.0"
}
