/*
 * Copyright (C) 2016 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
#include "utils/activity_manager.h"

#include <gmock/gmock.h>
#include <gtest/gtest.h>
#include "utils/device_info.h"
#include "utils/device_info_helper.h"

using std::string;
using testing::DoAll;
using testing::HasSubstr;
using testing::Return;
using testing::SaveArg;
using testing::SetArgPointee;
using testing::StartsWith;
using testing::StrEq;
using testing::StrNe;

namespace {
const char* const kAmExecutable = "/aaaaa/system/bin/am";
const char* const kProfileStart = "profile start";
const char* const kTestPackageName = "TestPackageName";
const char* const kMockOutputString = "MockOutputString";
const int kTestPid = 12345;
const char* const kTestFilePath = "/data/local/tmp/test_heapdump.hprof";
}  // namespace

namespace profiler {

// A subclass of ActivityManager that we want to test. The only difference is it
// has a public constructor.
class TestActivityManager final : public ActivityManager {
 public:
  explicit TestActivityManager(std::unique_ptr<BashCommandRunner> bash)
      : ActivityManager(std::move(bash)) {}
};

// A mock BashCommandRunner that mocks the execution of command.
// We need the mock to run tests across platforms to examine the commands
// generated by ActivityManager.
class MockBashCommandRunner final : public BashCommandRunner {
 public:
  explicit MockBashCommandRunner(const std::string& executable_path)
      : BashCommandRunner(executable_path) {}
  MOCK_CONST_METHOD2(RunAndReadOutput,
                     bool(const std::string& cmd, std::string* output_code));
};

TEST(ActivityManagerTest, SamplingStart_DualClockEnabled_Api34plus) {
  DeviceInfoHelper::SetDeviceInfo(
      DeviceInfo::UPSIDE_DOWN_CAKE);  // API level >= 34
  string trace_path;
  string output_code;
  string cmd;
  std::unique_ptr<BashCommandRunner> bash{
      new MockBashCommandRunner(kAmExecutable)};
  EXPECT_CALL(*(static_cast<MockBashCommandRunner*>(bash.get())),
              RunAndReadOutput(testing::A<const string&>(), &output_code))
      .WillOnce(DoAll(SaveArg<0>(&cmd), SetArgPointee<1>(kMockOutputString),
                      Return(true)));
  TestActivityManager manager{std::move(bash)};

  int64_t error_code = 0;
  manager.StartProfiling(ActivityManager::ProfilingMode::SAMPLING,
                         kTestPackageName, 1000, true, trace_path, &output_code,
                         &error_code);
  EXPECT_THAT(cmd, StartsWith(kAmExecutable));
  EXPECT_THAT(cmd, HasSubstr(kProfileStart));
  EXPECT_THAT(cmd, HasSubstr(kTestPackageName));
  EXPECT_THAT(cmd, Not(HasSubstr("--clock-type wall")));
  EXPECT_THAT(cmd, HasSubstr("--sampling 1000 "));
  // '--sampling 0' is effectively instrumentation mode.
  EXPECT_THAT(cmd, Not(HasSubstr("--sampling 0 ")));
  EXPECT_THAT(output_code, kMockOutputString);
}

TEST(ActivityManagerTest, SamplingStart_DualClockDisabled_Api34plus) {
  DeviceInfoHelper::SetDeviceInfo(
      DeviceInfo::UPSIDE_DOWN_CAKE);  // API level >= 34
  string trace_path;
  string output_code;
  string cmd;
  std::unique_ptr<BashCommandRunner> bash{
      new MockBashCommandRunner(kAmExecutable)};
  EXPECT_CALL(*(static_cast<MockBashCommandRunner*>(bash.get())),
              RunAndReadOutput(testing::A<const string&>(), &output_code))
      .WillOnce(DoAll(SaveArg<0>(&cmd), SetArgPointee<1>(kMockOutputString),
                      Return(true)));
  TestActivityManager manager{std::move(bash)};

  int64_t error_code = 0;
  manager.StartProfiling(ActivityManager::ProfilingMode::SAMPLING,
                         kTestPackageName, 1000, false, trace_path,
                         &output_code, &error_code);
  EXPECT_THAT(cmd, StartsWith(kAmExecutable));
  EXPECT_THAT(cmd, HasSubstr(kProfileStart));
  EXPECT_THAT(cmd, HasSubstr(kTestPackageName));
  EXPECT_THAT(cmd, HasSubstr("--clock-type wall"));
  EXPECT_THAT(cmd, HasSubstr("--sampling 1000 "));
  // '--sampling 0' is effectively instrumentation mode.
  EXPECT_THAT(cmd, Not(HasSubstr("--sampling 0 ")));
  EXPECT_THAT(output_code, kMockOutputString);
}

TEST(ActivityManagerTest, SamplingStart_DualClockEnabled_PreApi34) {
  DeviceInfoHelper::SetDeviceInfo(DeviceInfo::TIRAMISU);  // API level < 34
  string trace_path;
  string output_code;
  string cmd;
  std::unique_ptr<BashCommandRunner> bash{
      new MockBashCommandRunner(kAmExecutable)};
  EXPECT_CALL(*(static_cast<MockBashCommandRunner*>(bash.get())),
              RunAndReadOutput(testing::A<const string&>(), &output_code))
      .WillOnce(DoAll(SaveArg<0>(&cmd), SetArgPointee<1>(kMockOutputString),
                      Return(true)));
  TestActivityManager manager{std::move(bash)};

  int64_t error_code = 0;
  manager.StartProfiling(ActivityManager::ProfilingMode::SAMPLING,
                         kTestPackageName, 1000, false, trace_path,
                         &output_code, &error_code);
  EXPECT_THAT(cmd, StartsWith(kAmExecutable));
  EXPECT_THAT(cmd, HasSubstr(kProfileStart));
  EXPECT_THAT(cmd, HasSubstr(kTestPackageName));
  // 'clock-type' option is available for API >= 34
  EXPECT_THAT(cmd, Not(HasSubstr("--clock-type wall")));
  EXPECT_THAT(cmd, HasSubstr("--sampling 1000 "));
  // '--sampling 0' is effectively instrumentation mode.
  EXPECT_THAT(cmd, Not(HasSubstr("--sampling 0 ")));
  EXPECT_THAT(output_code, kMockOutputString);
}

TEST(ActivityManagerTest, SamplingStart_DualClockDisabled_PreApi34) {
  DeviceInfoHelper::SetDeviceInfo(DeviceInfo::TIRAMISU);  // API level < 34
  string trace_path;
  string output_code;
  string cmd;
  std::unique_ptr<BashCommandRunner> bash{
      new MockBashCommandRunner(kAmExecutable)};
  EXPECT_CALL(*(static_cast<MockBashCommandRunner*>(bash.get())),
              RunAndReadOutput(testing::A<const string&>(), &output_code))
      .WillOnce(DoAll(SaveArg<0>(&cmd), SetArgPointee<1>(kMockOutputString),
                      Return(true)));
  TestActivityManager manager{std::move(bash)};

  int64_t error_code = 0;
  manager.StartProfiling(ActivityManager::ProfilingMode::SAMPLING,
                         kTestPackageName, 1000, false, trace_path,
                         &output_code, &error_code);
  EXPECT_THAT(cmd, StartsWith(kAmExecutable));
  EXPECT_THAT(cmd, HasSubstr(kProfileStart));
  EXPECT_THAT(cmd, HasSubstr(kTestPackageName));
  // 'clock-type' option is available for API >= 34
  EXPECT_THAT(cmd, Not(HasSubstr("--clock-type wall")));
  EXPECT_THAT(cmd, HasSubstr("--sampling 1000 "));
  // '--sampling 0' is effectively instrumentation mode.
  EXPECT_THAT(cmd, Not(HasSubstr("--sampling 0 ")));
  EXPECT_THAT(output_code, kMockOutputString);
}

TEST(ActivityManagerTest, InstrumentStart_DualClockEnabled_Api34plus) {
  DeviceInfoHelper::SetDeviceInfo(
      DeviceInfo::UPSIDE_DOWN_CAKE);  // API level >= 34
  string trace_path;
  string output_code;
  string cmd;
  std::unique_ptr<BashCommandRunner> bash{
      new MockBashCommandRunner(kAmExecutable)};
  EXPECT_CALL(*(static_cast<MockBashCommandRunner*>(bash.get())),
              RunAndReadOutput(testing::A<const string&>(), &output_code))
      .WillOnce(DoAll(SaveArg<0>(&cmd), SetArgPointee<1>(kMockOutputString),
                      Return(true)));
  TestActivityManager manager{std::move(bash)};

  int64_t error_code = 0;
  manager.StartProfiling(ActivityManager::ProfilingMode::INSTRUMENTED,
                         kTestPackageName, 1000, true, trace_path, &output_code,
                         &error_code);
  EXPECT_THAT(cmd, StartsWith(kAmExecutable));
  EXPECT_THAT(cmd, HasSubstr(kProfileStart));
  EXPECT_THAT(cmd, HasSubstr(kTestPackageName));
  EXPECT_THAT(cmd, Not(HasSubstr("--clock-type wall")));
  EXPECT_THAT(cmd, Not(HasSubstr("--sampling")));
  EXPECT_THAT(output_code, kMockOutputString);
}

TEST(ActivityManagerTest, InstrumentStart_DualClockDisabled_Api34plus) {
  DeviceInfoHelper::SetDeviceInfo(
      DeviceInfo::UPSIDE_DOWN_CAKE);  // API level >= 34
  string trace_path;
  string output_code;
  string cmd;
  std::unique_ptr<BashCommandRunner> bash{
      new MockBashCommandRunner(kAmExecutable)};
  EXPECT_CALL(*(static_cast<MockBashCommandRunner*>(bash.get())),
              RunAndReadOutput(testing::A<const string&>(), &output_code))
      .WillOnce(DoAll(SaveArg<0>(&cmd), SetArgPointee<1>(kMockOutputString),
                      Return(true)));
  TestActivityManager manager{std::move(bash)};

  int64_t error_code = 0;
  manager.StartProfiling(ActivityManager::ProfilingMode::INSTRUMENTED,
                         kTestPackageName, 1000, false, trace_path,
                         &output_code, &error_code);
  EXPECT_THAT(cmd, StartsWith(kAmExecutable));
  EXPECT_THAT(cmd, HasSubstr(kProfileStart));
  EXPECT_THAT(cmd, HasSubstr(kTestPackageName));
  EXPECT_THAT(cmd, HasSubstr("--clock-type wall"));
  EXPECT_THAT(cmd, Not(HasSubstr("--sampling")));
  EXPECT_THAT(output_code, kMockOutputString);
}

TEST(ActivityManagerTest, InstrumentStart_DualClockEnabled_PreApi34) {
  DeviceInfoHelper::SetDeviceInfo(DeviceInfo::TIRAMISU);  // API level < 34
  string trace_path;
  string output_code;
  string cmd;
  std::unique_ptr<BashCommandRunner> bash{
      new MockBashCommandRunner(kAmExecutable)};
  EXPECT_CALL(*(static_cast<MockBashCommandRunner*>(bash.get())),
              RunAndReadOutput(testing::A<const string&>(), &output_code))
      .WillOnce(DoAll(SaveArg<0>(&cmd), SetArgPointee<1>(kMockOutputString),
                      Return(true)));
  TestActivityManager manager{std::move(bash)};

  int64_t error_code = 0;
  manager.StartProfiling(ActivityManager::ProfilingMode::INSTRUMENTED,
                         kTestPackageName, 1000, true, trace_path, &output_code,
                         &error_code);
  EXPECT_THAT(cmd, StartsWith(kAmExecutable));
  EXPECT_THAT(cmd, HasSubstr(kProfileStart));
  EXPECT_THAT(cmd, HasSubstr(kTestPackageName));
  EXPECT_THAT(cmd, Not(HasSubstr("--clock-type wall")));
  EXPECT_THAT(cmd, Not(HasSubstr("--sampling")));
  EXPECT_THAT(output_code, kMockOutputString);
}

TEST(ActivityManagerTest, InstrumentStart_DualClockDisabled_PreApi34) {
  DeviceInfoHelper::SetDeviceInfo(DeviceInfo::TIRAMISU);  // API level < 34
  string trace_path;
  string output_code;
  string cmd;
  std::unique_ptr<BashCommandRunner> bash{
      new MockBashCommandRunner(kAmExecutable)};
  EXPECT_CALL(*(static_cast<MockBashCommandRunner*>(bash.get())),
              RunAndReadOutput(testing::A<const string&>(), &output_code))
      .WillOnce(DoAll(SaveArg<0>(&cmd), SetArgPointee<1>(kMockOutputString),
                      Return(true)));
  TestActivityManager manager{std::move(bash)};

  int64_t error_code = 0;
  manager.StartProfiling(ActivityManager::ProfilingMode::INSTRUMENTED,
                         kTestPackageName, 1000, false, trace_path,
                         &output_code, &error_code);
  EXPECT_THAT(cmd, StartsWith(kAmExecutable));
  EXPECT_THAT(cmd, HasSubstr(kProfileStart));
  EXPECT_THAT(cmd, HasSubstr(kTestPackageName));
  EXPECT_THAT(cmd, Not(HasSubstr("--clock-type wall")));
  EXPECT_THAT(cmd, Not(HasSubstr("--sampling")));
  EXPECT_THAT(output_code, kMockOutputString);
}

TEST(ActivityManagerTest, InstrumentSystemServerStart) {
  string trace_path;
  string output_code;
  string cmd;
  std::unique_ptr<BashCommandRunner> bash{
      new MockBashCommandRunner(kAmExecutable)};
  EXPECT_CALL(*(static_cast<MockBashCommandRunner*>(bash.get())),
              RunAndReadOutput(testing::A<const string&>(), &output_code))
      .WillOnce(DoAll(SaveArg<0>(&cmd), SetArgPointee<1>(kMockOutputString),
                      Return(true)));
  TestActivityManager manager{std::move(bash)};

  int64_t error_code = 0;
  manager.StartProfiling(ActivityManager::ProfilingMode::INSTRUMENTED,
                         "system_process", 1000, false, trace_path,
                         &output_code, &error_code);
  EXPECT_THAT(cmd, StartsWith(kAmExecutable));
  EXPECT_THAT(cmd, HasSubstr(kProfileStart));
  EXPECT_THAT(cmd, HasSubstr(" system "));
  EXPECT_THAT(cmd, Not(HasSubstr(" system_process ")));
  EXPECT_THAT(output_code, kMockOutputString);
}

TEST(ActivityManagerTest, TriggerHeapDump_Success_WithOptionB_ApiQPlus) {
  DeviceInfoHelper::SetDeviceInfo(DeviceInfo::Q);
  string error_string;
  string cmd;
  std::unique_ptr<BashCommandRunner> bash{
      new MockBashCommandRunner(kAmExecutable)};
  EXPECT_CALL(*(static_cast<MockBashCommandRunner*>(bash.get())),
              RunAndReadOutput(testing::A<const string&>(), &error_string))
      .WillOnce(DoAll(SaveArg<0>(&cmd), Return(true)));
  TestActivityManager manager{std::move(bash)};

  bool result = manager.TriggerHeapDump(kTestPid, kTestFilePath, &error_string);

  EXPECT_TRUE(result);
  EXPECT_THAT(cmd, StartsWith(kAmExecutable));
  EXPECT_THAT(cmd, HasSubstr("dumpheap -b png"));
  EXPECT_THAT(cmd, HasSubstr(std::to_string(kTestPid)));
  EXPECT_THAT(cmd, HasSubstr(kTestFilePath));
  EXPECT_TRUE(error_string.empty());
}

TEST(ActivityManagerTest, TriggerHeapDump_Fallback_WhenOptionBFails_ApiQPlus) {
  DeviceInfoHelper::SetDeviceInfo(DeviceInfo::Q);
  string error_string;
  string cmd_option_b;
  string cmd_fallback;
  std::unique_ptr<BashCommandRunner> bash{
      new MockBashCommandRunner(kAmExecutable)};

  testing::InSequence s;
  EXPECT_CALL(*(static_cast<MockBashCommandRunner*>(bash.get())),
              RunAndReadOutput(testing::A<const string&>(), &error_string))
      .WillOnce(DoAll(SaveArg<0>(&cmd_option_b),
                      SetArgPointee<1>("Error with -b"), Return(false)));
  EXPECT_CALL(*(static_cast<MockBashCommandRunner*>(bash.get())),
              RunAndReadOutput(testing::A<const string&>(), &error_string))
      .WillOnce(DoAll(SaveArg<0>(&cmd_fallback), Return(true)));

  TestActivityManager manager{std::move(bash)};

  bool result = manager.TriggerHeapDump(kTestPid, kTestFilePath, &error_string);

  EXPECT_TRUE(result);
  EXPECT_THAT(cmd_option_b, StartsWith(kAmExecutable));
  EXPECT_THAT(cmd_option_b, HasSubstr("dumpheap -b png"));
  EXPECT_THAT(cmd_option_b, HasSubstr(std::to_string(kTestPid)));
  EXPECT_THAT(cmd_option_b, HasSubstr(kTestFilePath));

  EXPECT_THAT(cmd_fallback, StartsWith(kAmExecutable));
  EXPECT_THAT(cmd_fallback, HasSubstr("dumpheap"));
  EXPECT_THAT(cmd_fallback, Not(HasSubstr("-b png")));
  EXPECT_THAT(cmd_fallback, HasSubstr(std::to_string(kTestPid)));
  EXPECT_THAT(cmd_fallback, HasSubstr(kTestFilePath));
  // error_string should be cleared by the fallback logic
  EXPECT_TRUE(error_string.empty());
}

TEST(ActivityManagerTest, TriggerHeapDump_Success_WithoutOptionB_ApiPreQ) {
  DeviceInfoHelper::SetDeviceInfo(DeviceInfo::P);  // API Level < Q
  string error_string;
  string cmd;
  std::unique_ptr<BashCommandRunner> bash{
      new MockBashCommandRunner(kAmExecutable)};
  EXPECT_CALL(*(static_cast<MockBashCommandRunner*>(bash.get())),
              RunAndReadOutput(testing::A<const string&>(), &error_string))
      .WillOnce(DoAll(SaveArg<0>(&cmd), Return(true)));
  TestActivityManager manager{std::move(bash)};

  bool result = manager.TriggerHeapDump(kTestPid, kTestFilePath, &error_string);

  EXPECT_TRUE(result);
  EXPECT_THAT(cmd, StartsWith(kAmExecutable));
  EXPECT_THAT(cmd, HasSubstr("dumpheap"));
  EXPECT_THAT(cmd, Not(HasSubstr("-b png")));
  EXPECT_THAT(cmd, HasSubstr(std::to_string(kTestPid)));
  EXPECT_THAT(cmd, HasSubstr(kTestFilePath));
  EXPECT_TRUE(error_string.empty());
}

TEST(ActivityManagerTest, TriggerHeapDump_Failure_ApiPreQ) {
  DeviceInfoHelper::SetDeviceInfo(DeviceInfo::P);  // API Level < Q
  string error_string;
  string cmd;
  std::unique_ptr<BashCommandRunner> bash{
      new MockBashCommandRunner(kAmExecutable)};
  EXPECT_CALL(*(static_cast<MockBashCommandRunner*>(bash.get())),
              RunAndReadOutput(testing::A<const string&>(), &error_string))
      .WillOnce(DoAll(SaveArg<0>(&cmd),
                      SetArgPointee<1>("Generic dumpheap error"),
                      Return(false)));
  TestActivityManager manager{std::move(bash)};

  bool result = manager.TriggerHeapDump(kTestPid, kTestFilePath, &error_string);

  EXPECT_FALSE(result);
  EXPECT_THAT(cmd, StartsWith(kAmExecutable));
  EXPECT_THAT(cmd, HasSubstr("dumpheap"));
  EXPECT_THAT(cmd, Not(HasSubstr("-b png")));
  EXPECT_THAT(cmd, HasSubstr(std::to_string(kTestPid)));
  EXPECT_THAT(cmd, HasSubstr(kTestFilePath));
  EXPECT_EQ(error_string, "Generic dumpheap error");
}

}  // namespace profiler
