/*
 * Copyright (C) 2025 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

plugins {
    id 'com.android.tools.java-library'
    id 'com.android.tools.kotlin'
    id 'com.android.tools.publish'
    id 'com.android.tools.metalava'
}

dependencies {
    implementation libs.kotlin_stdlib

    metalavaTestImplementation libs.com.android.tools.testutils
    metalavaTestImplementation libs.guava
    metalavaTestImplementation libs.junit
    metalavaTestImplementation libs.kotlin_test

    // Ensure gradle-common-api, gradle-api, gradle-settings-api have some version
    constraints {
        api project(':base:gradle-api')
        api project(':base:build-system:gradle-settings-api')
    }
}

group = 'com.android.tools.build'
version = rootProject.ext.buildVersion

project.ext.pomName = 'Gradle Common API'
project.ext.pomDesc = 'Common APIs for Android Gradle tools.'


def updateApi = tasks.register('updateApi') {
    dependsOn('updateMetalavaApi')
}
