load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "mapped_file",
    srcs = ["mapped_file.cc"],
    hdrs = ["mapped_file.h"],
    deps = [
        "@com_google_absl//absl/log",
    ],
)
