// ATTENTION -- hash value of this file is checked in the corresponding
// integration test. Please make sure any changes you make here are
// backwards compatible.

apply plugin: 'com.android.library'

android {
    namespace = "com.android.tests.libstest.lib2"
    compileSdkVersion libs.versions.latestCompileSdk.get().toInteger()
    buildToolsVersion = libs.versions.buildToolsVersion.get()
    defaultConfig {
        minSdkVersion libs.versions.supportLibMinSdk.get()
	//noinspection ExpiredTargetSdkVersion
	targetSdkVersion libs.versions.supportLibMinSdk.get()
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
}

def variantCount = 0
// query for all (non-test) variants and inject a new step in the builds
androidComponents {
    onVariants(selector().all()) { variant ->
        variantCount++
        // create a task that copies some additional data in the library bundle
        def copyBlahTask = tasks.register("copy${variant.name.capitalize()}Blah", Copy) {
            from(layout.projectDirectory.dir("blah"))
            into(layout.buildDirectory.dir("bundles/${variant.name}"))
        }

        tasks.matching { it.name == "bundle${variant.name.capitalize()}Aar" }.configureEach {
            it.dependsOn(copyBlahTask)
        }
    }
}

dependencies {
    androidTestImplementation "androidx.test:runner:1.4.0-alpha06"
    androidTestImplementation "androidx.test:rules:1.4.0-alpha06"
}

project.afterEvaluate {
    if (variantCount != 2) {
        throw new GradleException("Wrong number of app variants! Expected 2, got $variantCount")
    }
}
