load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "test-inspector-api",
    srcs = glob(["src/**/*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "@maven//:androidx.annotation.annotation",
    ],
)
