load("//tools/base/intellij-bazel:intellij.bzl", "intellij_platform_setting")
load("//tools/base/intellij-bazel:transitioned_java.bzl", "DEFAULT_INTELLIJ_PLATFORM")

intellij_platform_setting(
    name = "intellij_platform",
    build_setting_default = DEFAULT_INTELLIJ_PLATFORM,
    visibility = ["//visibility:public"],
)
