intellij = use_extension("//tools/base/intellij-bazel:extensions.bzl", "intellij")

# IntelliJ platforms. To add support:
# The URLs have to point to full IDEs. While there are some versions
# of the IDEs in https://www.jetbrains.com/intellij-repository,
# they do not contain the bundled JBRs. These IDEs are used to run
# integration tests, so they have to be fully functional. This means we are
# not able to compile against snapshot builds that have not been released.
#
# To calculate the sha256, download the file and run sha256sum on it.
intellij.local_platform(
    name = "studio-sdk",
    spec = "@//prebuilts/studio/intellij-sdk:AI/spec.bzl",
    target = "@//prebuilts/studio/intellij-sdk:studio-sdk",
)
intellij.local_platform(
    name = "sherlock-sdk",
    spec = "@//prebuilts/studio/intellij-sdk:IC/spec.bzl",
    target = "@//prebuilts/studio/intellij-sdk:sherlock-sdk",
)

# IMPORTANT: This list of repos should always be kept up to date with the platforms defined above.
use_repo(intellij, "intellij")
