plugins {
    id 'com.android.library'
    id 'instrumentation-plugin'
}

android {
    namespace = "com.example.lib"
    compileSdkVersion libs.versions.latestCompileSdk.get().toInteger()
}

apply from: "../../commonHeader.gradle"  // for $kotlinVersion

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib:${libs.versions.kotlinVersion.get()}"
}
