load(
    ":release_version.bzl",
    _IS_AGP_RELEASE_BRANCH = "IS_AGP_RELEASE_BRANCH",
    _LAST_STABLE_BUILD_VERSION = "LAST_STABLE_BUILD_VERSION",
    _RELEASE_BASE_VERSION = "BASE_VERSION",
    _RELEASE_BUILD_VERSION = "BUILD_VERSION",
    _RELEASE_COMMANDLINE_TOOLS_VERSION = "COMMANDLINE_TOOLS_VERSION",
)

LAST_STABLE_BUILD_VERSION = _LAST_STABLE_BUILD_VERSION
IS_AGP_RELEASE_BRANCH = _IS_AGP_RELEASE_BRANCH

DEV_BASE_VERSION = _RELEASE_BASE_VERSION.split("-")[0] + "-dev"
RELEASE_BASE_VERSION = _RELEASE_BASE_VERSION if _IS_AGP_RELEASE_BRANCH == "true" else DEV_BASE_VERSION
BASE_VERSION = select({
    "//tools/base/bazel:release": RELEASE_BASE_VERSION,
    "//conditions:default": DEV_BASE_VERSION,
})

DEV_BUILD_VERSION = _RELEASE_BUILD_VERSION.split("-")[0] + "-dev"
RELEASE_BUILD_VERSION = _RELEASE_BUILD_VERSION if _IS_AGP_RELEASE_BRANCH == "true" else DEV_BUILD_VERSION
BUILD_VERSION = select({
    "//tools/base/bazel:release": RELEASE_BUILD_VERSION,
    "//conditions:default": DEV_BUILD_VERSION,
})

DEV_COMMANDLINE_TOOLS_VERSION = _RELEASE_COMMANDLINE_TOOLS_VERSION.split("-")[0] + "-dev"
RELEASE_COMMANDLINE_TOOLS_VERSION = _RELEASE_COMMANDLINE_TOOLS_VERSION if _IS_AGP_RELEASE_BRANCH == "true" else DEV_COMMANDLINE_TOOLS_VERSION
COMMANDLINE_TOOLS_VERSION = select({
    "//tools/base/bazel:release": RELEASE_COMMANDLINE_TOOLS_VERSION,
    "//conditions:default": DEV_COMMANDLINE_TOOLS_VERSION,
})
