configurations {
    apiJars
}

dependencies {
    apiJars gradleApi() // Note that gradleApi() returns multiple jars
}

task copyGradleApiJars(type: Copy) {
    // Get the whole gradle distribution
    from configurations.apiJars.incoming.artifacts.resolvedArtifacts
        .map { it.find { it.file.name.startsWith('gradle-installation-beacon')  }.file.parentFile.parentFile }
    // And the gradle-api jar itself, which is generated
    from configurations.apiJars.incoming.artifacts.resolvedArtifacts
        .map { it.find { it.file.name.startsWith('gradle-api')  }.file }
    into System.env["BUILD_DIR"]
}
