/*
 * Copyright (C) 2021 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

syntax = "proto3";
option java_package = "com.android.adblib.tools.debugging.processinventory.protos";
option java_outer_classname = "ProcessInventoryServerProto";
option optimize_for = LITE_RUNTIME;
package adblib.tools.protos;

/*
 * The protocol for "ProcessInventoryServer" is as follows
 *
 * Sending a request to the server:
 *    bytes 0-3: 32-bit integer (little endian): length of "Request" proto to follow
 *    bytes 4-n: array of bytes: "Request" proto message
 *
 * Receiving a response from the server:
 *    bytes 0-3: 32-bit integer (little endian): length of "Response" proto to follow
 *    bytes 4-n: array of bytes: "Response" proto message
 *
 * If "Request" was for a "stream" of "Response", the socket remains open, and many
 * "Response" packets are sent to the socket until the socket closes.
 */
message Request {
    /*
     * An arbitrary string describing/identifying the client making the request. This string
     * is only used for logging and diagnostics.
     */
    string client_description = 1;

    /*
     * The request payload, depending on the request [type]
     */
    oneof payload {
        TrackDeviceRequestPayload track_device_request_payload = 10;
        UpdateDeviceRequestPayload update_device_request_payload = 11;
    }

    /*
     * Ask the server to start emitting `TrackDeviceResponsePayload` responses as process updates
     * are sent to the server.
     */
    message TrackDeviceRequestPayload {
        DeviceId device_id = 1;
    }

    /*
     * Request to notify of updates to one or more processes, including "process termination"
     */
    message UpdateDeviceRequestPayload {
        DeviceId device_id = 1;
        ProcessUpdates process_updates = 2;
    }

}

message Response {
    /*
     * An arbitrary string describing/identifying the server instance, used only for logging and
     * diagnostic. The name is transient, i.e. a server restart may (a probably will) result in
     * a new value.
     */
    string server_description = 1;

    /*
     * Whether the request was successful, i.e. whether the [payload] field contains
     * the reply
     */
    bool ok = 2;

    /*
     * If [ok] is `false`, an optional error message
     */
    optional string error_message = 3;

    oneof payload {
        TrackDeviceResponsePayload track_device_response_payload = 11;
        UpdateDeviceResponsePayload update_device_response_payload = 12;
    }

    /*
     * The list of process changes since the last response was sent.
     *
     * Note: This response is sent multiple times until the connection is closed.
     */
    message TrackDeviceResponsePayload {
        ProcessUpdates process_updates = 1;
    }

    message UpdateDeviceResponsePayload {
        // Nothing, just an "ACK"
    }
}

/*
 * A device identifier as stored in the 'ProcessInventoryServer'
 */
message DeviceId {
    /*
     * An identifier of the ADB/adblib session used to distinguish between device
     * serial numbers on different ADB connections.
     *
     * Note: This is currently unused, but is reserved for future use if support for
     * multiple ADB connections is required.
     */
    string adb_session_id = 1;

    /*
     * The device serial number, identifying a device for a given adb_session_id
     */
    string serial_number = 2;
}

/*
 * Changes from a previously sent `ProcessUpdates` message
 */
message ProcessUpdates {
  repeated ProcessUpdate process_update = 1;
}

/*
 * A single process change: a process may have been added, removed or one or more of its fields
 * may have changed.
 */
message ProcessUpdate {
    oneof process_update {
        // A new process has been added or an existing process has been updated
        JdwpProcessInfo process_updated = 1;
        // A previously known process has exited
        int32 process_terminated_pid = 2;
    }
}

message JdwpProcessInfo {
    /*
     * The JDWP process ID, always present
     */
    int32 pid = 1;

    /*
     * The process name (see JdwpProcessProperties class)
     */
    OptionalString process_name = 2;

    /*
     * The package name (see JdwpProcessProperties class)
     */
    OptionalString package_name = 3;

    /*
     * The User ID this process is running in context of (see JdwpProcessProperties class)
     */
    OptionalInt32 user_id = 4;

    /*
     * The AndroidVM instruction set architecture (isa) (see JdwpProcessProperties class)
     */
    OptionalString instruction_set = 5;

    /*
     * The Android VM identifier (see JdwpProcessProperties class)
     */
    OptionalString vm_identifier = 6;

    /*
     * The JVM flags (see JdwpProcessProperties class)
     */
    OptionalString jvm_flags = 7;

    /*
     * Whether legacy native debugging is supported (see JdwpProcessProperties class)
     */
    OptionalBool native_debuggable = 8;

    /**
     * Whether the process is waiting for a debugger to attach (see JdwpProcessProperties class)
     */
    OptionalBool waiting_for_debugger = 9;

    /*
     * List of features reported by the [DdmsFeatChunk] packet (see JdwpProcessProperties class)
     */
    OptionalStringList features = 10;
}

message OptionalString {
    // has_value == false && is_error == false  =>  empty value
    // has_value == true  && is_error == false  =>  valid non-null value
    // has_value == false && is_error == true   =>  error with error message
    // has_value == true  && is_error == true   =>  should never happen
    bool has_value = 1;
    bool is_error = 2;
    optional string error_message = 3;
    optional string string_value = 4;
}

message OptionalBool {
    // has_value == false && is_error == false  =>  empty value
    // has_value == true  && is_error == false  =>  valid non-null value
    // has_value == false && is_error == true   =>  error with error message
    // has_value == true  && is_error == true   =>  should never happen
    bool has_value = 1;
    bool is_error = 2;
    optional string error_message = 3;
    optional bool bool_value = 4;
}

message OptionalInt32 {
    // has_value == false && is_error == false  =>  empty value
    // has_value == true  && is_error == false  =>  valid non-null value
    // has_value == false && is_error == true   =>  error with error message
    // has_value == true  && is_error == true   =>  should never happen
    bool has_value = 1;
    bool is_error = 2;
    optional string error_message = 3;
    optional int32 in32_value = 4;
}

message OptionalStringList {
    // has_value == false && is_error == false  =>  empty value
    // has_value == true  && is_error == false  =>  valid non-null value
    // has_value == false && is_error == true   =>  error with error message
    // has_value == true  && is_error == true   =>  should never happen
    bool has_value = 1;
    bool is_error = 2;
    optional string error_message = 3;
    repeated string strings_value = 4;
}
