/*
 * Copyright (C) 2017 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.android.builder.errors

import com.android.builder.model.v2.ide.SyncIssue

/**
 * Base class for error reporting.
 *
 * This allows returning configuration/evaluation error to an IDE, by running in a lenient mode and only records but does not throw
 * exception. [IssueReporter.hasIssue] allows checking if a given issue has already been recorded.
 *
 * When using inside a build step, use [DefaultIssueReporter] which will always throw on error.
 */
abstract class IssueReporter {

  enum class Severity constructor(val severity: Int) {
    WARNING(SyncIssue.SEVERITY_WARNING),
    ERROR(SyncIssue.SEVERITY_ERROR),
  }

  @Suppress("DEPRECATION")
  enum class Type constructor(val type: Int) {
    GENERIC(SyncIssue.TYPE_GENERIC),
    PLUGIN_OBSOLETE(SyncIssue.TYPE_PLUGIN_OBSOLETE),
    UNRESOLVED_DEPENDENCY(SyncIssue.TYPE_UNRESOLVED_DEPENDENCY),
    DEPENDENCY_IS_APK(SyncIssue.TYPE_DEPENDENCY_IS_APK),
    DEPENDENCY_IS_APKLIB(SyncIssue.TYPE_DEPENDENCY_IS_APKLIB),
    NON_JAR_LOCAL_DEP(SyncIssue.TYPE_NON_JAR_LOCAL_DEP),
    NON_JAR_PACKAGE_DEP(SyncIssue.TYPE_NON_JAR_PACKAGE_DEP),
    NON_JAR_PROVIDED_DEP(SyncIssue.TYPE_NON_JAR_PROVIDED_DEP),
    JAR_DEPEND_ON_AAR(SyncIssue.TYPE_JAR_DEPEND_ON_AAR),
    MISMATCH_DEP(SyncIssue.TYPE_MISMATCH_DEP),
    OPTIONAL_LIB_NOT_FOUND(SyncIssue.TYPE_OPTIONAL_LIB_NOT_FOUND),
    JACK_IS_NOT_SUPPORTED(SyncIssue.TYPE_JACK_IS_NOT_SUPPORTED),
    GRADLE_TOO_OLD(SyncIssue.TYPE_GRADLE_TOO_OLD),
    BUILD_TOOLS_TOO_LOW(SyncIssue.TYPE_BUILD_TOOLS_TOO_LOW),
    DEPENDENCY_MAVEN_ANDROID(SyncIssue.TYPE_DEPENDENCY_MAVEN_ANDROID),
    DEPENDENCY_INTERNAL_CONFLICT(SyncIssue.TYPE_DEPENDENCY_INTERNAL_CONFLICT),
    EXTERNAL_NATIVE_BUILD_CONFIGURATION(SyncIssue.TYPE_EXTERNAL_NATIVE_BUILD_CONFIGURATION),
    EXTERNAL_NATIVE_BUILD_PROCESS_EXCEPTION(SyncIssue.TYPE_EXTERNAL_NATIVE_BUILD_PROCESS_EXCEPTION),
    JACK_REQUIRED_FOR_JAVA_8_LANGUAGE_FEATURES(SyncIssue.TYPE_JACK_REQUIRED_FOR_JAVA_8_LANGUAGE_FEATURES),
    DEPENDENCY_WEAR_APK_TOO_MANY(SyncIssue.TYPE_DEPENDENCY_WEAR_APK_TOO_MANY),
    DEPENDENCY_WEAR_APK_WITH_UNBUNDLED(SyncIssue.TYPE_DEPENDENCY_WEAR_APK_WITH_UNBUNDLED),
    JAR_DEPEND_ON_ATOM(SyncIssue.TYPE_JAR_DEPEND_ON_ATOM),
    AAR_DEPEND_ON_ATOM(SyncIssue.TYPE_AAR_DEPEND_ON_ATOM),
    ATOM_DEPENDENCY_PROVIDED(SyncIssue.TYPE_ATOM_DEPENDENCY_PROVIDED),
    MISSING_SDK_PACKAGE(SyncIssue.TYPE_MISSING_SDK_PACKAGE),
    STUDIO_TOO_OLD(SyncIssue.TYPE_STUDIO_TOO_OLD),
    UNNAMED_FLAVOR_DIMENSION(SyncIssue.TYPE_UNNAMED_FLAVOR_DIMENSION),
    INCOMPATIBLE_PLUGIN(SyncIssue.TYPE_INCOMPATIBLE_PLUGIN),
    DEPRECATED_DSL(SyncIssue.TYPE_DEPRECATED_DSL),
    MIN_SDK_VERSION_IN_MANIFEST(SyncIssue.TYPE_MIN_SDK_VERSION_IN_MANIFEST),
    TARGET_SDK_VERSION_IN_MANIFEST(SyncIssue.TYPE_TARGET_SDK_VERSION_IN_MANIFEST),
    UNSUPPORTED_PROJECT_OPTION_USE(SyncIssue.TYPE_UNSUPPORTED_PROJECT_OPTION_USE),
    MANIFEST_PARSED_DURING_CONFIGURATION(SyncIssue.TYPE_MANIFEST_PARSED_DURING_CONFIGURATION),
    THIRD_PARTY_GRADLE_PLUGIN_TOO_OLD(SyncIssue.TYPE_THIRD_PARTY_GRADLE_PLUGIN_TOO_OLD),
    SIGNING_CONFIG_DECLARED_IN_DYNAMIC_FEATURE(SyncIssue.TYPE_SIGNING_CONFIG_DECLARED_IN_DYNAMIC_FEATURE),
    SDK_NOT_SET(SyncIssue.TYPE_SDK_NOT_SET),
    AMBIGUOUS_BUILD_TYPE_DEFAULT(SyncIssue.TYPE_AMBIGUOUS_BUILD_TYPE_DEFAULT),
    AMBIGUOUS_PRODUCT_FLAVOR_DEFAULT(SyncIssue.TYPE_AMBIGUOUS_PRODUCT_FLAVOR_DEFAULT),
    COMPILE_SDK_VERSION_NOT_SET(SyncIssue.TYPE_COMPILE_SDK_VERSION_NOT_SET),
    ANDROID_X_PROPERTY_NOT_ENABLED(SyncIssue.TYPE_ANDROID_X_PROPERTY_NOT_ENABLED),
    USING_DEPRECATED_CONFIGURATION(SyncIssue.TYPE_USING_DEPRECATED_CONFIGURATION),
    USING_DEPRECATED_DSL_VALUE(SyncIssue.TYPE_USING_DEPRECATED_DSL_VALUE),
    EDIT_LOCKED_DSL_VALUE(SyncIssue.TYPE_EDIT_LOCKED_DSL_VALUE),
    MISSING_ANDROID_MANIFEST(SyncIssue.TYPE_MISSING_ANDROID_MANIFEST),
    JCENTER_IS_DEPRECATED(SyncIssue.TYPE_JCENTER_IS_DEPRECATED),
    AGP_USED_JAVA_VERSION_TOO_LOW(SyncIssue.TYPE_AGP_USED_JAVA_VERSION_TOO_LOW),
    COMPILE_SDK_VERSION_TOO_HIGH(SyncIssue.TYPE_COMPILE_SDK_VERSION_TOO_HIGH),
    COMPILE_SDK_VERSION_TOO_LOW(SyncIssue.TYPE_COMPILE_SDK_VERSION_TOO_LOW),
    ACCESSING_DISABLED_FEATURE_VARIANT_API(SyncIssue.TYPE_ACCESSING_DISABLED_FEATURE_VARIANT_API),
    APPLICATION_ID_MUST_NOT_BE_DYNAMIC(SyncIssue.TYPE_APPLICATION_ID_MUST_NOT_BE_DYNAMIC),
    REMOVED_API(SyncIssue.TYPE_REMOVED_API),
    EMPTY_FLAVOR_DIMENSION(SyncIssue.TYPE_EMPTY_FLAVOR_DIMENSION),
    EXCEPTION(SyncIssue.TYPE_EXCEPTION),
    NAMESPACE_NOT_SET(SyncIssue.TYPE_NAMESPACE_NOT_SET),
    INCONSISTENT_BUILD_FEATURE_SETTING(SyncIssue.TYPE_INCONSISTENT_BUILD_FEATURE_SETTING),
    MISSING_COMPOSE_COMPILER_GRADLE_PLUGIN(SyncIssue.TYPE_MISSING_COMPOSE_COMPILER_GRADLE_PLUGIN),
    LIBRARY_CONSTRAINTS_SHOULD_BE_DISABLED(SyncIssue.TYPE_LIBRARY_CONSTRAINTS_SHOULD_BE_DISABLED),
    RENDERSCRIPT_NOT_SUPPORTED_ON_RISCV(SyncIssue.TYPE_RENDERSCRIPT_NOT_SUPPORTED_ON_RISCV),
    KOTLIN_SOURCE_SET_NOT_ALLOWED(SyncIssue.TYPE_KOTLIN_SOURCE_SET_NOT_ALLOWED),
    NON_APK_RUNTIME_DEP(SyncIssue.TYPE_NON_APK_RUNTIME_DEP),
    CONNECTED_CHECK_TASK_NOT_FOUND(SyncIssue.TYPE_CONNECTED_CHECK_TASK_NOT_FOUND),
    MANIFEST_PARSE_FAILED(SyncIssue.TYPE_MANIFEST_PARSE_FAILED),
    RETROLAMBDA_USED(SyncIssue.TYPE_RETROLAMBDA_USED),
    FLAT_DIR_REPOSITORY_USED(SyncIssue.TYPE_FLAT_DIR_REPOSITORY_USED),
    ACCESSING_DEPRECATED_LEGACY_MODEL(SyncIssue.TYPE_ACCESSING_DEPRECATED_LEGACY_MODEL),
    CANNOT_SET_ON_MERGED_FLAVOR(SyncIssue.TYPE_CANNOT_SET_ON_MERGED_FLAVOR),
    COMPILE_SDK_PREVIEW_INVALID(SyncIssue.TYPE_COMPILE_SDK_PREVIEW_INVALID),
    NAMESPACE_INVALID(SyncIssue.TYPE_NAMESPACE_INVALID),
    PROGUARD_FILE_INVALID(SyncIssue.TYPE_PROGUARD_FILE_INVALID),
    TEST_OPTIONS_TARGET_SDK_INVALID(SyncIssue.TYPE_TEST_OPTIONS_TARGET_SDK_INVALID),
    KGP_LOADED_IN_DIFFERENT_CLASSLOADER(SyncIssue.TYPE_KGP_LOADED_IN_DIFFERENT_CLASSLOADER),
    UNSUPPORTED_EXECUTION_PROFILE(SyncIssue.TYPE_UNSUPPORTED_EXECUTION_PROFILE),
    LINT_VERSION_OVERRIDE_INVALID(SyncIssue.TYPE_LINT_VERSION_OVERRIDE_INVALID),
    NAMESPACE_CONFLICT(SyncIssue.TYPE_NAMESPACE_CONFLICT),
    INVALID_VERSION_CODE(SyncIssue.TYPE_INVALID_VERSION_CODE),
    PURE_SPLITS_NOT_SUPPORTED(SyncIssue.TYPE_PURE_SPLITS_NOT_SUPPORTED),
    MINIFY_ENABLED_IN_DYNAMIC_FEATURE(SyncIssue.TYPE_MINIFY_ENABLED_IN_DYNAMIC_FEATURE),
    ABI_FILTERS_IN_DYNAMIC_FEATURE(SyncIssue.TYPE_ABI_FILTERS_IN_DYNAMIC_FEATURE),
    INVALID_PUBLISHING_CONFIG(SyncIssue.TYPE_INVALID_PUBLISHING_CONFIG),
    RESOURCE_SHRINK_NOT_SUPPORTED(SyncIssue.TYPE_RESOURCE_SHRINK_NOT_SUPPORTED),
    RES_VALUE_REPLACED(SyncIssue.TYPE_RES_VALUE_REPLACED),
    BUILD_CONFIG_USED_WHEN_DISABLED(SyncIssue.TYPE_BUILD_CONFIG_USED_WHEN_DISABLED),
    RES_VALUES_USED_WHEN_DISABLED(SyncIssue.TYPE_RES_VALUES_USED_WHEN_DISABLED),
    UNRECOGNIZED_SOURCE_SET(SyncIssue.TYPE_UNRECOGNIZED_SOURCE_SET),
    APPLICATION_ID_SUFFIX_IGNORED(SyncIssue.TYPE_APPLICATION_ID_SUFFIX_IGNORED),
    APPLICATION_ID_NOT_ALLOWED_IN_LIBRARY(SyncIssue.TYPE_APPLICATION_ID_NOT_ALLOWED_IN_LIBRARY),
    APPLICATION_ID_SUFFIX_NOT_ALLOWED_IN_LIBRARY(SyncIssue.TYPE_APPLICATION_ID_SUFFIX_NOT_ALLOWED_IN_LIBRARY),
    CONFLICTING_ABI_CONFIG(SyncIssue.TYPE_CONFLICTING_ABI_CONFIG),
    CANNOT_BUILD_SELECTED_TARGET_ABI(SyncIssue.TYPE_CANNOT_BUILD_SELECTED_TARGET_ABI),
    DEBUGGABLE_AND_MINIFIED_ENABLED(SyncIssue.TYPE_DEBUGGABLE_AND_MINIFIED_ENABLED),
    MIN_SDK_VERSION_GREATER_THAN_TARGET_SDK(SyncIssue.TYPE_MIN_SDK_VERSION_GREATER_THAN_TARGET_SDK),
    TEST_SUITE_IGNORED(SyncIssue.TYPE_TEST_SUITE_IGNORED),
    JAVA9_COMPILATION_REQUIRES_COMPILE_SDK30(SyncIssue.TYPE_JAVA9_COMPILATION_REQUIRES_COMPILE_SDK30),
    JAVA_COMPILE_RELEASE_OPTION_NOT_SUPPORTED(SyncIssue.TYPE_JAVA_COMPILE_RELEASE_OPTION_NOT_SUPPORTED),
    JAVA_COMPILE_DEPRECATED_SOURCE_TARGET(SyncIssue.TYPE_JAVA_COMPILE_DEPRECATED_SOURCE_TARGET),
    SDK_RESOLUTION_WARNING(SyncIssue.TYPE_SDK_RESOLUTION_WARNING),
    ASSET_PACK_PROJECT_NOT_FOUND(SyncIssue.TYPE_ASSET_PACK_PROJECT_NOT_FOUND),
    R8_VERSION_MISMATCH(SyncIssue.TYPE_R8_VERSION_MISMATCH),
    R8_GRADUAL_API_FLAG_REQUIRED(SyncIssue.TYPE_R8_GRADUAL_API_FLAG_REQUIRED),
    DYNAMIC_FEATURE_PROJECT_NOT_FOUND(SyncIssue.TYPE_DYNAMIC_FEATURE_PROJECT_NOT_FOUND),
    FUSED_LIBRARY_PUBLICATION_ONLY_MODE(SyncIssue.TYPE_FUSED_LIBRARY_PUBLICATION_ONLY_MODE),
    ASSET_PACK_BUNDLE_INVALID_CONFIG(SyncIssue.TYPE_ASSET_PACK_BUNDLE_INVALID_CONFIG),
    TEST_SUITE_SUPPORT_EXPERIMENTAL(SyncIssue.TYPE_TEST_SUITE_SUPPORT_EXPERIMENTAL),
    LINT_TARGET_SDK_LESS_THAN_ANDROID_TARGET_SDK(SyncIssue.TYPE_LINT_TARGET_SDK_LESS_THAN_ANDROID_TARGET_SDK),
    ACCESS_TO_DEPRECATED_LEGACY_API_REQUIRES_COMPATIBILITY_MODE(SyncIssue.TYPE_ACCESS_TO_DEPRECATED_LEGACY_API_REQUIRES_COMPATIBILITY_MODE),
    UNKNOWN_SOURCE_KIND(SyncIssue.TYPE_UNKNOWN_SOURCE_KIND),
    GET_APPLICATION_ID_NOT_SUPPORTED_IN_DYNAMIC_FEATURE(SyncIssue.TYPE_GET_APPLICATION_ID_NOT_SUPPORTED_IN_DYNAMIC_FEATURE),
    AIDL_DISABLED_VIA_BUILD_FEATURES(SyncIssue.TYPE_AIDL_DISABLED_VIA_BUILD_FEATURES),
    RENDERSCRIPT_DISABLED_VIA_BUILD_FEATURES(SyncIssue.TYPE_RENDERSCRIPT_DISABLED_VIA_BUILD_FEATURES),
    DATABINDING_KTX_NO_EFFECT(SyncIssue.TYPE_DATABINDING_KTX_NO_EFFECT),
    DATABINDING_ANNOTATION_PROCESSOR_VERSION_MISMATCH(SyncIssue.TYPE_DATABINDING_ANNOTATION_PROCESSOR_VERSION_MISMATCH),
    MULTIDEX_NOT_NEEDED(SyncIssue.TYPE_MULTIDEX_NOT_NEEDED),
    RELATIVE_PATH_NOT_SUPPORTED_IN_OUTPUT_FILE_NAME(SyncIssue.TYPE_RELATIVE_PATH_NOT_SUPPORTED_IN_OUTPUT_FILE_NAME),
    CORE_LIBRARY_DESUGARING_REQUIRES_D8_OR_R8(SyncIssue.TYPE_CORE_LIBRARY_DESUGARING_REQUIRES_D8_OR_R8),
    CORE_LIBRARY_DESUGARING_REQUIRES_MULTIDEX(SyncIssue.TYPE_CORE_LIBRARY_DESUGARING_REQUIRES_MULTIDEX),
    DEFAULT_PROGUARD_FILE_IN_NON_BASE_MODULE(SyncIssue.TYPE_DEFAULT_PROGUARD_FILE_IN_NON_BASE_MODULE),
    DEFAULT_PROGUARD_FILE_AS_CONSUMER_FILE(SyncIssue.TYPE_DEFAULT_PROGUARD_FILE_AS_CONSUMER_FILE),
    RESOURCE_SHRINK_REQUIRES_CODE_SHRINK(SyncIssue.TYPE_RESOURCE_SHRINK_REQUIRES_CODE_SHRINK),
    MULTIPLE_IDENTICAL_CALLS_TO_ANDROID_COMPONENTS_API(SyncIssue.TYPE_MULTIPLE_IDENTICAL_CALLS_TO_ANDROID_COMPONENTS_API),
    PROGUARD_ANDROID_OPTIMIZE_TXT_DISALLOWED(SyncIssue.TYPE_PROGUARD_ANDROID_OPTIMIZE_TXT_DISALLOWED),
    UNKNOWN_PROGUARD_FILE(SyncIssue.TYPE_UNKNOWN_PROGUARD_FILE),
    DEBUGGABLE_AND_PROFILEABLE_ENABLED(SyncIssue.TYPE_DEBUGGABLE_AND_PROFILEABLE_ENABLED),
    ANDROID_TEST_NOT_DEFINED(SyncIssue.TYPE_ANDROID_TEST_NOT_DEFINED),
    DYNAMIC_FEATURE_MULTIDEX_SET_IN_DSL(SyncIssue.TYPE_DYNAMIC_FEATURE_MULTIDEX_SET_IN_DSL),
  }

  protected abstract fun reportIssue(type: Type, severity: Severity, exception: EvalIssueException)

  /**
   * Reports an error.
   *
   * When running outside of IDE sync, this will throw an exception and abort execution.
   *
   * @param type the type of the error.
   * @param msg a human readable error (for command line output, or if an older IDE doesn't know this particular issue type.)
   * @param data a data representing the source of the error. This goes hand in hand with the <var>type</var>, and is not meant to be
   *   readable. Instead a (possibly translated) message is created from this data and type.
   * @param multilineMsg a human readable error that spans through multiple lines (might require special IDE treatment.)
   */
  @JvmOverloads
  fun reportError(type: Type, msg: String, data: String? = null, multilineMsg: List<String>? = null) {
    reportIssue(type, Severity.ERROR, EvalIssueException(msg, data, multilineMsg))
  }

  /**
   * Reports an error.
   *
   * When running outside of IDE sync, this will throw an exception and abort execution.
   *
   * @param type the type of the error.
   * @param cause exception containing all relevant information about the error.
   */
  fun reportError(type: Type, cause: Exception) {
    reportIssue(type, Severity.ERROR, EvalIssueException(cause))
  }

  /**
   * Reports a warning.
   *
   * Behaves similar to [reportError] but does not abort the build.
   *
   * @param type the type of the error.
   * @param msg a human readable error (for command line output, or if an older IDE doesn't know this particular issue type.)
   * @param data a data representing the source of the error. This goes hand in hand with the <var>type</var>, and is not meant to be
   *   readable. Instead a (possibly translated) message is created from this data and type.
   * @param multilineMsg a human readable error that spans through multiple lines (might require special IDE treatment.)
   */
  @JvmOverloads
  fun reportWarning(type: Type, msg: String, data: String? = null, multilineMsg: List<String>? = null) {
    val suppressionMsg =
      if (type in TYPES_WITHOUT_GENERAL_SUPPRESSION) ""
      else "\nAdd android.sync.suppressAgpWarnings=${type.name} to the gradle.properties file to suppress this warning."
    reportIssue(type, Severity.WARNING, EvalIssueException(msg + suppressionMsg, data, multilineMsg))
  }

  /**
   * Reports a warning.
   *
   * Behaves similar to [reportError] but does not abort the build.
   *
   * @param type the type of the error.
   * @param cause exception containing all relevant information about the error.
   */
  fun reportWarning(type: Type, cause: Exception) {
    reportIssue(type, Severity.WARNING, EvalIssueException(cause))
  }

  /** Whether an issue of the given type has been recorded. */
  abstract fun hasIssue(type: Type): Boolean

  companion object {
    private val TYPES_WITHOUT_GENERAL_SUPPRESSION = setOf(Type.COMPILE_SDK_VERSION_TOO_HIGH)
  }
}
