/*
 * Copyright (C) 2025 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.android.tools.utp.gradle

import com.android.tools.utp.gradle.api.UtpDependencies
import com.google.testing.platform.launcher.Launcher
import com.google.testing.platform.proto.api.config.RunnerConfigProto.RunnerConfig
import com.google.testing.platform.proto.api.core.TestStatusProto.TestStatus
import com.google.testing.platform.proto.api.core.TestSuiteResultProto.TestSuiteResult
import java.io.File
import java.util.concurrent.ExecutionException
import java.util.concurrent.ExecutorService
import java.util.concurrent.Executors
import java.util.concurrent.TimeUnit
import org.gradle.api.GradleException
import org.gradle.api.logging.Logger
import org.gradle.api.logging.Logging

/**
 * Runs UTP test suites.
 *
 * This class is designed to be used within a Gradle Worker. It manages the full lifecycle of the test run, specifically delegating the
 * parallel execution of multiple UTP instances to a provided [ExecutorService].
 *
 * @param utpDependencies Resolved UTP dependency artifacts.
 * @param logger A Gradle logger instance.
 * @param executorServiceFactory A factory function to create the [ExecutorService] used for parallel process execution.
 * @param utpExecutor The function used to execute a single UTP instance given its [RunnerConfig].
 */
class UtpRunner(
  private val utpDependencies: UtpDependencies,
  private val logger: Logger = Logging.getLogger(UtpRunner::class.java),
  private val executorServiceFactory: () -> ExecutorService = Executors::newCachedThreadPool,
  private val utpExecutor: UtpRunner.(RunnerConfig) -> Unit = UtpRunner::execute,
) {
  companion object {
    private const val TEST_RESULT_EXIT_CODE_SUCCESS = 0
    private const val TEST_RESULT_EXIT_CODE_FAILURE = 1
  }

  /**
   * Executes the given [utpRunnerConfigList] in parallel, merges the results, and writes the final output.
   *
   * This function manages the lifecycle of the UTP execution:
   * 1. Submits runner tasks to an executor service.
   * 2. Aggregates results from [utpResultProtoOutputFileList].
   * 3. Writes the merged Protobuf result and the final exit code to their respective files.
   *
   * @param utpRunnerConfigList The list of UTP runner configurations (one per shard/run) to execute.
   * @param utpResultProtoOutputFileList The list of intermediate output files generated by the runners. These are read to produce the
   *   merged result.
   * @param mergedUtpResultProtoOutputFile The destination file where the final merged test result Protobuf will be written.
   * @param testResultExitCodeFile The destination file where the final integer exit code (success/failure) will be written.
   * @throws GradleException If any of the parallel UTP tasks fail during execution.
   */
  fun execute(
    utpRunnerConfigList: List<RunnerConfig>,
    utpResultProtoOutputFileList: List<File>,
    mergedUtpResultProtoOutputFile: File,
    testResultExitCodeFile: File,
  ) {
    val executorService = executorServiceFactory()
    try {
      val futures = utpRunnerConfigList.map { runConfig -> executorService.submit { utpExecutor(runConfig) } }.toList()

      var hasExecutionFailures = false
      futures.forEach {
        try {
          it.get()
        } catch (e: ExecutionException) {
          logger.warn("Test Execution failed", e)
          hasExecutionFailures = true
        }
      }

      if (hasExecutionFailures) {
        throw GradleException("Test Execution failed")
      }
    } finally {
      try {
        executorService.shutdownNow()
        executorService.awaitTermination(5, TimeUnit.SECONDS)
      } finally {
        val resultsMerger = UtpTestSuiteResultMerger()
        utpResultProtoOutputFileList
          .filter { it.exists() && it.isFile }
          .map { it.inputStream().use { TestSuiteResult.parseFrom(it) } }
          .forEach { resultsMerger.merge(it) }

        val result = resultsMerger.result
        if (result.platformError.errorsCount > 0) {
          logger.error(getPlatformErrorMessage(result))
        }
        result.issueList.forEach { issue -> logger.error(issue.message) }
        mergedUtpResultProtoOutputFile.outputStream().use { result.writeTo(it) }

        val testResultExitCode: Int =
          if (result.testStatus.isPassedOrSkipped()) {
            TEST_RESULT_EXIT_CODE_SUCCESS
          } else {
            TEST_RESULT_EXIT_CODE_FAILURE
          }
        testResultExitCodeFile.writeText(testResultExitCode.toString())
      }
    }
  }

  private fun TestStatus.isPassedOrSkipped(): Boolean {
    return when (this) {
      TestStatus.PASSED,
      TestStatus.IGNORED,
      TestStatus.SKIPPED -> true
      else -> false
    }
  }

  /**
   * Executes a single UTP run for a given configuration.
   *
   * @param utpRunnerConfig The runner configuration proto for this specific UTP execution.
   */
  private fun execute(utpRunnerConfig: RunnerConfig) {
    val utpRunnerConfigFile = createUtpTempFile("runnerConfig", ".pb")
    utpRunnerConfigFile.writeBytes(utpRunnerConfig.toByteArray())
    Launcher.launchRunner(
      arrayOf(utpDependencies.core.files.joinToString(File.pathSeparator), "--proto_config=${utpRunnerConfigFile.absolutePath}")
    ) {}
  }
}
