apply plugin: 'com.android.application'

android {
    namespace = "com.android.tests.basic"
    compileSdkVersion libs.versions.latestCompileSdk.get().toInteger()
    buildToolsVersion = libs.versions.buildToolsVersion.get()

    defaultConfig {
        minSdkVersion 16
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        create("minified").initWith(buildTypes.debug)
        minified {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt')
        }
    }
}

dependencies {
    api project(':lib')

    testImplementation 'junit:junit:4.12'
    androidTestImplementation "androidx.test:runner:1.4.0-alpha06"
    androidTestImplementation "androidx.test:rules:1.4.0-alpha06"
    androidTestImplementation "androidx.annotation:annotation-experimental:1.3.0"
}
