load("@rules_java//java:defs.bzl", "java_import")

java_import(
    name = "inspection-testing",
    jars = [
        "inspection-testing-1.0.0.jar",
    ],
    visibility = ["//visibility:public"],
)
