apply plugin: 'com.android.tools.java'
apply plugin: 'com.android.tools.kotlin'

repositories {
    maven { url = uri(rootProject.cloneArtifacts.repository) }
}

dependencies {
    testImplementation project(':base:build-system:integration-test:framework')
    testImplementation libs.com.android.tools.analyticsLibrary.protos
    testImplementation libs.com.android.tools.apkparser.apkanalyzer
    testImplementation libs.com.android.tools.build.apksig
    testImplementation project(':base:builder-model')
    testImplementation project(':base:build-analyzer:common')
    testImplementation project(':base:build-system:gradle-core')
    testImplementation project(':base:build-system:gradle-kotlin')
    testImplementation project(':base:build-system:gradle-settings-api')
    testImplementation project(':base:build-system:shrinker')
    testImplementation project(':base:profgen')
    testImplementation libs.com.android.tools.sdkCommon
    testImplementation libs.com.android.tools.sdklib
    testImplementation externalTestFixtures.repository
    testImplementation libs.com.android.tools.testutils
    testImplementation libs.com.android.zipflinger
    testCompileOnly(project(':base:profile'))
    testImplementation libs.com.android.tools.layoutlib.layoutlibApi
    testImplementation project(':base:profgen')
    testImplementation project(':base:preview:screenshot:screenshot-test-gradle-plugin')

    testImplementation libs.kotlin_stdlib
    testImplementation libs.kotlin_test
    testImplementation libs.kotlin_coroutines_core

    testImplementation gradleApi()
    testImplementation libs.asm_tree
    testImplementation libs.smali_dexlib
    testImplementation libs.apache_commons_io
    testImplementation libs.apache_commons_lang
    testImplementation libs.apache_compress
    testImplementation libs.bundle_tool
    testImplementation libs.google_api_client
    testImplementation libs.google_storage_client
    testImplementation libs.junit
    testImplementation 'org.junit.platform:junit-platform-engine:1.9.2'
    testImplementation libs.junit_platform_reporting
    testImplementation libs.protobuf
    testImplementation libs.protobuf_util
    testImplementation libs.truth
    testImplementation libs.unified_test_platform
    testImplementation libs.ksp_gradle_plugin  // to acces the KSP extension in custom test project plugins

    testImplementation libs.kotlin_gradle_plugin // to get access to KotlinJvmCompilerOptions and other Kotlin DSL types
    testImplementation libs.compose_compiler_gradle_plugin // to get access to ComposeCompilerGradlePluginExtension

    testImplementation libs.mockito_core

    // Add dependency on plugin code.  Exclude transitive dependencies to avoid conflict due to
    // Groovy versions.
    testImplementation(project(':base:build-system:gradle-core')) {
        transitive = false
    }
}

configurations {
    // google-api-client depends on guava-jdk5.
    testImplementation.exclude group: 'com.google.guava', module: 'guava-jdk5'
}

apply from: '../integration-tests.gradle'

File tempFile = new File(project.buildDir, 'tmp')
tempFile.mkdirs()

test {
    description =
            "Runs the project integration tests. This requires an SDK either from the Android " +
                    "source tree, under out/..., or an env var ANDROID_SDK_ROOT."
    systemProperties['jar.path'] = jar.archiveFile.get().getAsFile().path
    systemProperties['java.io.tmpdir'] = tempFile.absolutePath
    environment = testEnvironment

    outputs.upToDateWhen { false }

    Float maxParallelForksRatio = 3.0
    if (System.properties["os.arch"] == "aarch64") {
        maxParallelForksRatio = 1.5
    }
    if (project.hasProperty("com.android.build.integ-tests.parallelForkRatio")) {
        maxParallelForksRatio = Float.parseFloat(
                project.getProperties().get("com.android.build.integ-tests.parallelForkRatio")
        )
    }
    maxParallelForks = Runtime.runtime.availableProcessors() / maxParallelForksRatio

    useJUnit {
        String includedCategories = System.getProperty('test.includeCategories')
        if (includedCategories != null) {
            def categories = includedCategories.split(',')
            String defaultPackage = "com.android.build.gradle.integration.common.category."
            categories = categories.collect { it.charAt(0).isUpperCase() ? defaultPackage + it : it }
            includeCategories categories as String[]
        }
        excludeCategories "com.android.build.gradle.integration.common.category.OnlineTests"
    }

    exclude "com/android/build/gradle/integration/automatic/**"
    exclude "**/BazelIntegrationTestsSuite*"
	environment["PROJECT_ROOT"] = project.projectDir
}

sourceSets {
    automaticTest {
        java.srcDir file("src/integrationTest/java")
        compileClasspath += sourceSets.main.output + configurations.testCompileClasspath
        runtimeClasspath += sourceSets.main.output + configurations.testRuntimeClasspath
    }
}

task automaticTest(type: Test) {
    include "com/android/build/gradle/integration/automatic/**"

    testClassesDirs = sourceSets.automaticTest.output.classesDirs
    classpath = sourceSets.automaticTest.runtimeClasspath
    // Always run the task, when requested.
    outputs.upToDateWhen { false }
    environment = testEnvironment
}

check.dependsOn automaticTest

automaticTest.dependsOn ':publishLocal'
test.dependsOn ':publishAndroidGradleLocal'

if (tasks.findByName("jacocoTestReport") != null) {
    jacocoTestReport {
        sourceSets project(':base:build-system:gradle-core').sourceSets.main
        sourceSets project(':base:builder').sourceSets.main
        sourceSets project(':base:builder-model').sourceSets.main
        sourceSets project(':base:builder-test-api').sourceSets.main
    }

    // Due to memory constraints, apply jacoco only when jacocoTestReport is invoked.  Make sure to
    // rerun tests when generating report jacoco.
    gradle.taskGraph.whenReady { TaskExecutionGraph taskGraph ->
        if (taskGraph.hasTask(jacocoTestReport)) {
            test.environment("ATTACH_JACOCO_AGENT", "yes")
        }
    }
}
