load("//tools/base/bazel:kotlin.bzl", "kotlin_library", "kotlin_test")

kotlin_library(
    name = "reporter_lib",
    srcs = glob([
        "src/main/kotlin/**/*.kt",
    ]),
    visibility = ["//visibility:public"],
    deps = [
        "//tools/base/android-test/coverage/proto:coverage_metadata_java_proto_host",
        "@maven//:com.google.protobuf.protobuf-java",
    ],
)

kotlin_test(
    name = "reporter_tests",
    size = "small",
    srcs = glob([
        "src/test/kotlin/**/*.kt",
    ]),
    jvm_flags = ["-Dtest.suite.jar=reporter_tests.jar"],
    test_class = "com.android.testutils.JarTestSuite",
    deps = [
        ":reporter_lib",
        "//tools/base/android-test/coverage/proto:coverage_metadata_java_proto_host",
        "//tools/base/testutils:tools.testutils",
        "@maven//:com.google.protobuf.protobuf-java",
        "@maven//:com.google.truth.truth",
        "@maven//:junit.junit",
    ],
)
