{
  "formatVersion": "1.1",
  "component": {
    "url": "../../tracing-wire/2.0.0-SNAPSHOT/tracing-wire-2.0.0-SNAPSHOT.module",
    "group": "androidx.tracing",
    "module": "tracing-wire",
    "version": "2.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1",
      "buildId:": "14576191"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.squareup.wire",
          "module": "wire-runtime",
          "version": {
            "requires": "5.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          },
          "reason": "tracing-wire is in atomic group androidx.tracing"
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-ktx",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          },
          "reason": "tracing-wire is in atomic group androidx.tracing"
        }
      ],
      "files": [
        {
          "name": "tracing-wire-desktop-2.0.0-SNAPSHOT.jar",
          "url": "tracing-wire-desktop-2.0.0-SNAPSHOT.jar",
          "size": 139233,
          "sha512": "8239fc44c74bcfa4e25a298735614f9275ab2997c9e7ea7bf6fecfa4210eed2498ae0b829aa1d3c90d8237dc6f658a6b805bfcabb0e817de10f891e9ebd709aa",
          "sha256": "ab7862d601f871c5055546813a40945c9d00a188afe47b5566500d34659552c9",
          "sha1": "3e2f09d9ede6376bb51084a2a1e40e19245f0ab7",
          "md5": "2c5a01f30b639f23b4d66f075192bccf"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        },
        {
          "group": "com.squareup.wire",
          "module": "wire-runtime",
          "version": {
            "requires": "5.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          },
          "reason": "tracing-wire is in atomic group androidx.tracing"
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-ktx",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          },
          "reason": "tracing-wire is in atomic group androidx.tracing"
        }
      ],
      "files": [
        {
          "name": "tracing-wire-desktop-2.0.0-SNAPSHOT.jar",
          "url": "tracing-wire-desktop-2.0.0-SNAPSHOT.jar",
          "size": 139233,
          "sha512": "8239fc44c74bcfa4e25a298735614f9275ab2997c9e7ea7bf6fecfa4210eed2498ae0b829aa1d3c90d8237dc6f658a6b805bfcabb0e817de10f891e9ebd709aa",
          "sha256": "ab7862d601f871c5055546813a40945c9d00a188afe47b5566500d34659552c9",
          "sha1": "3e2f09d9ede6376bb51084a2a1e40e19245f0ab7",
          "md5": "2c5a01f30b639f23b4d66f075192bccf"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          },
          "reason": "tracing-wire is in atomic group androidx.tracing"
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-ktx",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          },
          "reason": "tracing-wire is in atomic group androidx.tracing"
        }
      ],
      "files": [
        {
          "name": "tracing-wire-desktop-2.0.0-SNAPSHOT-sources.jar",
          "url": "tracing-wire-desktop-2.0.0-SNAPSHOT-sources.jar",
          "size": 42130,
          "sha512": "25bd27a1c608404be967667ab5aebbb2d690a805ac26dc73220e5b86fcf13607d758a5d584420e2fccf8e633cb26fc78b358c9575b31f349f3e7424748342919",
          "sha256": "1ce4e208f08fdbd3ab506bb060a571c23191927f08286ecb2e76896d5d9c2acb",
          "sha1": "05d0abd1c4b0010b99d1a1dca7c85f389a8a88bb",
          "md5": "a65a520393e30b0ca643d0210a786e14"
        }
      ]
    }
  ]
}