{
  "formatVersion": "1.1",
  "component": {
    "url": "../../tracing-wire/2.0.0-SNAPSHOT/tracing-wire-2.0.0-SNAPSHOT.module",
    "group": "androidx.tracing",
    "module": "tracing-wire",
    "version": "2.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1",
      "buildId:": "14746442"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.squareup.wire",
          "module": "wire-runtime",
          "version": {
            "requires": "5.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          },
          "reason": "tracing-wire is in atomic group androidx.tracing"
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-ktx",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          },
          "reason": "tracing-wire is in atomic group androidx.tracing"
        }
      ],
      "files": [
        {
          "name": "tracing-wire-desktop-2.0.0-SNAPSHOT.jar",
          "url": "tracing-wire-desktop-2.0.0-SNAPSHOT.jar",
          "size": 154651,
          "sha512": "7d0ce0e2257045ec1dd13f8d422c888bb451fed7ffb302ebff56e537c461fa122f821fce4d476a3e3023fb46e9b79ecafb51ecb34fa30cb04fdaf8bfbdae3d85",
          "sha256": "530bf9c17d05e018704aced19b4859c81e6d3edb832ac1fc67f26ca2455ea5ba",
          "sha1": "ba61373db27752ee21d86f4100d81891fdcfc272",
          "md5": "b3daa3bb081ab081051ade963d5afebe"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        },
        {
          "group": "com.squareup.wire",
          "module": "wire-runtime",
          "version": {
            "requires": "5.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          },
          "reason": "tracing-wire is in atomic group androidx.tracing"
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-ktx",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          },
          "reason": "tracing-wire is in atomic group androidx.tracing"
        }
      ],
      "files": [
        {
          "name": "tracing-wire-desktop-2.0.0-SNAPSHOT.jar",
          "url": "tracing-wire-desktop-2.0.0-SNAPSHOT.jar",
          "size": 154651,
          "sha512": "7d0ce0e2257045ec1dd13f8d422c888bb451fed7ffb302ebff56e537c461fa122f821fce4d476a3e3023fb46e9b79ecafb51ecb34fa30cb04fdaf8bfbdae3d85",
          "sha256": "530bf9c17d05e018704aced19b4859c81e6d3edb832ac1fc67f26ca2455ea5ba",
          "sha1": "ba61373db27752ee21d86f4100d81891fdcfc272",
          "md5": "b3daa3bb081ab081051ade963d5afebe"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          },
          "reason": "tracing-wire is in atomic group androidx.tracing"
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-ktx",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          },
          "reason": "tracing-wire is in atomic group androidx.tracing"
        }
      ],
      "files": [
        {
          "name": "tracing-wire-desktop-2.0.0-SNAPSHOT-sources.jar",
          "url": "tracing-wire-desktop-2.0.0-SNAPSHOT-sources.jar",
          "size": 45331,
          "sha512": "97849f85131148f31022e3a796a4880e5e3e7a18ea1b0be7cbc973fc1caa007f13e2e8fa748f547e8cf8efd2806d239265f4b652d21ca3ce884c73b6b627d869",
          "sha256": "39cc6239769954a34559007e645c56fdaca6d5d41376213d6d70e2ba3e4bf78c",
          "sha1": "4606874965ae97ce294e6e009f1dda95b5126113",
          "md5": "d5c1d51d7bfbab4eb137ea8ada44c61a"
        }
      ]
    }
  ]
}