apply plugin: 'com.android.application'

android {
    namespace = "com.example.android.multiproject"
    compileSdkVersion libs.versions.latestCompileSdk.get().toInteger()
    buildToolsVersion = libs.versions.buildToolsVersion.get()
    enableKotlin = false
}

dependencies {
    api project(path: ':util', configuration: 'custom')
}
