apply plugin: 'com.android.application'

android {
    namespace = "com.android.tests.libstest.app"
    compileSdkVersion libs.versions.latestCompileSdk.get().toInteger()
    buildToolsVersion = libs.versions.buildToolsVersion.get()
    defaultConfig {
        minSdkVersion 15
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
}

//
// A basic Android application split over a library and a main project.
//
dependencies {
    api project(':lib')

    testImplementation 'junit:junit:4.12'
    androidTestImplementation "androidx.test:runner:1.4.0-alpha06"
    androidTestImplementation "androidx.test:rules:1.4.0-alpha06"
}
